const basics={
    h1:"Información General",
    figure1:"Figura ",
    figure2:" de 5.  Da clic en las flechas para ver más resultados.",
    program:"Nombre del programa",
    organization:"Nombre de la organización (si es diferente del Nombre del programa)",
    orgtype:"Tipo de organización",
    country:"País o países en donde se lleva a cabo el programa (si aplica):",
    region:"Provincias o región/es (si corresponde):",
    name:"Nombre y apellido de quién completa el formulario",
    date:"Fecha de llenado del formulario:",
    stage:"Etapa del proyecto",
    save:"Guardar Datos",
    sendmail:"Enviarme los datos por correo electrónico",
    comment:"Comentarios"
}
const stages=['piloto','recién iniciado','mediano plazo','fase final','terminado'];
const orgtypes=["Gobierno local/representante de gobierno","organización de la sociedad civil/sin fines de lucro"];
const comment="Comentarios adicionales y retroalimentación";
const clickto="Guardar comentarios";

const dimensions=[
"A: Participación, inclusión, y voz",
"B: Recursos locales y conocimiento",
"C: Sostenibilidad y estrategia de transición",
"D: Mecanismos de rendición de cuentas",
"E: Capacidad de respuesta al contexto",
"F: Colaboración",
"G: Trabajo con gobierno local/organizaciones de la sociedad civil",
"H. Prácticas de monitoreo y evaluación",
"I. Facilitación"];

const rubric={
p2:["A1.El programa garantiza la inclusión de todos los grupos de personas que conforman la comunidad (como personas mayores y jóvenes, hombres y mujeres, de diferentes clases sociales, religiones, grupos étnicos, castas, etc.).",
"No sabe/ Información insuficiente para contestar.",
"El programa no considera o contempla a los diferentes grupos que conforman la comunidad.",
"El programa tiene en cuenta a algunos grupos excluidos (no a todos) y garantiza su participación en reuniones/actividades colectivas.",
"El programa tiene en cuenta a la mayoría de los grupos que conforman la comunidad y garantiza su participación en las reuniones/actividades colectivas",
"El programa tiene en cuenta a todos los grupos que conforman la comunidad y garantiza su participación activa en las reuniones/actividades colectivas"],
p3:["A2. Los miembros de la comunidad deciden/decidieron las prioridades del programa ANTES de su diseño",
"No sabe/ Información insuficiente para contestar.",  
"Los miembros de la comunidad no participan/participaron en la definición de las prioridades del programa",
"Un grupo selecto de miembros de la comunidad (p. ej., líderes y referentes históricos y tradicionales, terratenientes, etc.) participan/participaron en la definición de las prioridades del programa",
"La mayoría de los grupos que conforman la comunidad participan/participaron en la definición de las prioridades del programa", 
"Todos los grupos que conforman la comunidad  participan/participaron en la definición de las prioridades del programa y han sido escuchados de la misma manera"],
p4:["A3. Los miembros de la comunidad desempeñan/desempeñaron un papel activo en la planificación del programa de desarrollo liderado por la comunidad", 
"No sabe/ Información insuficiente para contestar.",
"Los miembros de la comunidad no participan/participaron en el proceso de planificación del programa", 
"Un grupo selecto de miembros de la comunidad (por ejemplo, líderes o representantes) participa/participó en la planificación del programa", 
"La mayoría de los grupos que conforman la comunidad participan/participaron en el proceso de planificación",
"Todos los grupos que conforman la comunidad participan/participaron en el proceso de planificación y su voz es/fue escuchada por igual"],
p5:["A4. El programa es implementado por órganos comunitarios que representan a todos los grupos y barrios",
"No sabe/ Información insuficiente para contestar.",
"Las ONGs o los líderes locales implementan el programa",
"Las ONG y/o los líderes locales crean un organismo comunitario para que implemente el programa o trabajan con un organismo existente que no necesariamente incorpora miembros de todos los grupos de la comunidad",
"El programa es implementado por organos con miembros autodesignados que representan a todos los grupos y barrios de la comunidad",
"El programa es implementado por órganos elegidos que representan a todos los grupos y barrios de la comunidad"],
p6:["A5. El programa refuerza la voz y la confianza de los representantes de la comunidad para influir en la toma de decisiones",
"No sabe/ Información insuficiente para contestar.",
"El programa no hace ningún esfuerzo por reforzar la voz o la confianza de los representantes de la comunidad",
"El programa fomenta la voz y la confianza de algunos representantes de la comunidad, pero no de los grupos excluidos",
"El programa fortalece la voz y la confianza de muchos representantes de la comunidad, incluidos los de algunos grupos excluidos",
"El programa refuerza la voz y la confianza de todos los representantes de la comunidad, incluidos los de todos los grupos excluidos"],
p7:["A6. El programa sensibiliza sobre los derechos (sociales, económicos y políticos) y fortalece capacidades entre los miembros locales para pedir por esos derechos",
"No sabe/ Información insuficiente para contestar.",
"El programa no sensibiliza ni fortalece capacidades para pedir derechos",
"El programa sensibiliza sobre los derechos, pero no fortalece capacidades para pedirlos", 
"El programa sensibiliza sobre los derechos y fortalece las capacidades de unas pocas personas para pedirlos",
"El programa sensibiliza sobre los derechos y se centra en el fortalecimiento de capacidades entre representantes locales de todos los grupos para pedirlos"],
p8:["B1. El programa liderado por la comunidad se basa en los recursos y conocimientos locales",
"No sabe/ Información insuficiente para contestar.",
"El programa no tiene en cuenta los recursos y conocimientos locales",
"El programa explora los recursos locales, pero el personal a cargo infunde y transmite conocimientos externos",
"El programa utiliza recursos locales y está al tanto de los conocimientos locales",
"El programa utiliza y respeta los conocimientos y recursos locales"],
p9:["B2. La comunidad aporta sus recursos (por ejemplo, tiempo, dinero, mano de obra, tierras, materiales, etc.)",
"No sabe/ Información insuficiente para contestar.",
"Los miembros de la comunidad no contribuyen en la ejecución del programa ni con dinero, especies o mano de obra",
"Los miembros de la comunidad contribuyen con tiempo/trabajo o recursos (tierra, dinero, materiales) porque es obligatorio",
"Los miembros de la comunidad contribuyen con tiempo/trabajo o recursos (tierra, efectivo, materiales), cuando se les anima a hacerlo",
"Los miembros de la comunidad deciden lo que se necesita, identifican por su cuenta los recursos adicionales (tiempo/trabajo, tierra, efectivo, materiales) y los ofrecen voluntariamente"],
p10:["C1. Las comunidades son fundamentales para planificar cómo y cuándo debe completarse el programa y en qué momento toman/tomarán las riendas del mismo", 
"No sabe/ Información insuficiente para contestar.",
"No existe un plan para la finalización y el traspaso del programa a la comunidad",
"La organización encargada de la ejecución elabora el plan de finalización y traspaso del programa y los líderes o miembros de la comunidad son informados al respecto",
"El plan de finalización y traspaso del programa se elabora en consulta con los líderes locales y los miembros de la comunidad",
"El plan de finalización y traspaso del programa está dirigido por miembros de la comunidad y líderes locales"],
p11:["C2. Las comunidades trabajan con las organizaciones ejecutoras para revisar y adaptar constantemente la planificación para el traspaso de programas y la transición",
"No sabe/ Información insuficiente para contestar.",
"No existe ningún plan o estrategia para el traspaso de los programas a la comunidad",
"Los planes para traspasar el programa a la comunidad sólo se hacen cuando el programa está llegando a su fin (o no queda financiación)",
"Los planes para traspasar el programa a la comunidad se elaboran al inicio del programa y se revisan al final del mismo o si se produce un contratiempo importante",
"Los planes para traspasar el programa a la comunidad se elaboran al inicio del programa y se revisan periódicamente con los miembros de la comunidad para reflejar la situación actual de la comunidad"],
p12:["C3. El programa se asegura de que las estructuras comunitarias (como las organizaciones de base comunitaria y los grupos que implementan los programas) cuenten con las capacidades necesarias para seguir trabajando luego del traspaso",
"No sabe/ Información insuficiente para contestar.",
"El programa no hace ningún esfuerzo para garantizar que las estructuras comunitarias puedan continuar trabajando después del traspaso",
"Hay un plan para el traspaso del programa pero no hay una estrategia para asegurar que las estructuras comunitarias puedan seguir trabajando y tengan las capacidades para obtener fondos y recursos en la medida de lo necesario.", 
"Hay una estrategia para asegurar que las estructuras comunitarias puedan seguir trabajando después del traspaso pero no hay actividades para fortalecer capacidades para obtener fondos y recursos en la medida de lo necesario.", 
"El programa implementa actividades para fortalecer capacidades para asegurarse que las estructuras comunitarias puedan continuar trabajando después del traspaso y conseguir  fondos y recursos en la medida de lo necesario."],
p13:["C4. Una vez finalizado, el impacto del programa se mide con la participación local",
"No sabe/ Información insuficiente para contestar.",
"No hay planes para medir el impacto del programa tras su finalización o la comunidad no está al tanto de si existen planes al respecto", 
"Hay planes para medir el impacto del programa (o se medirá) tras su finalización. Los miembros de la comunidad están informados sobre el ejercicio y proporcionan información cuando se les solicita",
"El impacto será medido - o plenea medirse- tras la finalización del programa y los miembros de la comunidad serán consultados durante el ejercicio.", 
"El impacto será medido (o está previsto que se mida) tras la finalización del programa y los miembros de la comunidad participan activamente en todas las fases del ejercicio."],
p14:["C5. Después que el programa haya sido traspasado a la estructuras comunitarias/del gobierno local, los miembros de la comunidad pertenecientes a todos los grupos (por ejemplo, mujeres, jóvenes, personas mayores, personas en situación de pobreza, personas con discapacidad, minorías, etc.) siguen beneficiándose de actividades lideradas por la comunidad",
"No sabe/ Información insuficiente para contestar.",
"Nadie obtiene ningún beneficio tras el traspaso del programa o sólo lo hacen ciertos grupos privilegiados",
"El programa sigue beneficiando a algunos grupos incluso después del traspaso",
"El programa sigue beneficiando a la mayoría de los grupos incluso después del traspaso",
"El programa sigue beneficiando a todos los grupos incluso después del traspaso"],
p15:["D1. El programa y las estructuras comunitarias comparten información importante, por ejemplo, qué están haciendo, por qué, de qué manera y cómo se utilizaron los fondos",
"No sabe/ Información insuficiente para contestar.",
"El programa no comparte ninguna información sobre lo que se está haciendo, ni el cómo ni el por qué con la comunidad",
"El programa o los organismos comunitarios a veces comparten información básica sobre el programa, pero la mayoría de los detalles no están disponibles",
"El programa o los organismos comunitarios comparten a menudo información en torno al programa (la mayor parte de la información está disponible, pero no toda)",
"El programa y los organismos comunitarios comparten con regularidad información sobre fondos, procesos y actividades con miembros de la comunidad a los que solicitan retroalimentación"],
p16:["D2. El programa aborda las inquietudes/quejas de la comunidad",
"No sabe/ Información insuficiente para contestar.",
"El programa no dispone de ningún medio para que los miembros de la comunidad presenten consultas/inquietudes/quejas",
"El programa tiene una vía para que los miembros de la comunidad presenten consultas/inquietudes/quejas, pero no es de fácil acceso ni confiable",
"El programa dispone de un medio accesible y confiable para que los miembros de la comunidad presenten sus consultas/inquietudes/quejas, pero éstas no son atendidas",
"El programa dispone de un medio accesible y confiable para que los miembros de la comunidad presenten consultas/inquietudes/quejas y éstas son atendidas"],
p17:["D3. Los resultados de los monitoreos y evaluaciones se comparten regularmente con los miembros de la comunidad",
"No sabe/ Información insuficiente para contestar.",
"Los resultados de monitoreos y evaluaciones nunca se comparten con los miembros de la comunidad",
"Los resultados de monitoreos y evaluaciones pueden ser eventualmente compartidos con miembros de la comunidad por parte de las personas implicadas en el programa cuando estas últimas lo consideran oportuno",
"Los resultados de monitoreos y evaluaciones sólo se comparten con los miembros de la comunidad cuando surgen problemas",
"Los resultados de monitoreos y evaluaciones se comparten regularmente con los miembros de la comunidad"],
p18:["E1. El programa da cuenta y responde a las necesidades y contextos cambiantes de la comunidad",
"No sabe/ Información insuficiente para contestar.",
"El programa no da cuenta ni responde a las necesidades cambiantes de la comunidad (por ejemplo, inundaciones, sequías, hambre estacional, llegada de nuevas tecnologías, cambios en los sistemas políticos, etc.)",
"El programa es capaz de realizar algunos ajustes",
"El programa es capaz de adaptarse según sea necesario a las necesidades y contextos cambiantes de la comunidad, incluidas aquéllas provocadas por crisis o catástrofes",
"El programa es capaz de adaptarse a las necesidades cambiantes de la comunidad, incluidas las provocadas por crisis o catástrofes, y promueve la creación de mecanismos o estructuras para abordar situaciones similares en el futuro"],
p19:["E2. El ritmo del programa de Desarrollo Liderado por las Comunidades (DLC) - por ejemplo el calendario, la frecuencia y duración de las instancias de interacción con la comunidad- son establecidas con los miembros de la comunidad",
"No sabe/ Información insuficiente para contestar.",
"La comunidad no participa en la determinación del ritmo del programa",
"La comunidad es informada acerca del ritmo del programa",
"Algunos miembros de la comunidad son consultados para decidir el ritmo del programa",
"Todos los miembros de la comunidad -incluidos los representantes de los grupos marginados-  son participados a la hora de definir el ritmo del programa"],
p20:["F1. El programa fomenta relaciones positivas entre personas en posiciones económicas privilegiadas y personas en situación de pobreza - y al interior de estas últimas.",
"No sabe/ Información insuficiente para contestar.",
"El programa no tiene en cuenta las diferencias económicas",
"El programa construye relaciones entre pobres y pobres",
"El programa involucra a personas en posiciones económicas privilegiadas y personas en situación de pobreza en debates y diálogos",
"El programa compromete a personas en posiciones económicas privilegiadas y personas en situación de pobreza a trabajar juntas para lograr un objetivo común"],
p21:["F2. El programa contribuye a crear relaciones positivas dentro y entre diferentes grupos étnicos, de casta, religiosos, etc.",
"No sabe/ Información insuficiente para contestar.",
"El programa no tiene en cuenta las diferencias de casta/etnia/religión",
"El programa contribuye crear relaciones entre personas de la misma casta/etnia/religión para que trabajen juntas para lograr el cambio social",
"El programa involucra a personas de diferentes castas/etnias/religiones en debates y diálogos",
"El programa contribuye crear relaciones entre personas de diferentes castas/etnias/religiones para que trabajen juntas para lograr el cambio social"],
p22:["F3. El programa fomenta vínculos positivos entre mujeres y entre hombres y mujeres",
"No sabe/ Información insuficiente para contestar.",
"El programa no trabaja con mujeres",
"El programa  fomenta vínculos entre mujeres del mismo grupo",
"El programa fomenta vínculos entre todos los grupos de mujeres o entre mujeres y hombres",
"El programa fomenta vínculos entre todos los grupos de mujeres y entre mujeres y hombres"],
p23:["F4. El programa vincula a comunidades locales o a sus líderes con otros pueblos y sus líderes en diferentes distritos, provincias o estados.",
"No sabe/ Información insuficiente para contestar.",
"El programa no construye redes y vínculos entre comunidades.",
"El programa fomenta vínculos entre comunidades/líderes  del mismo distrito.",
"El programa fomenta vínculos entre comunidades/líderes locales de diferentes distritos/estados/provincias/países.",
"El programa fomenta vínculos entre comunidades de diferentes estados/regiones/naciones para la acción colectiva."],
p24:["G1. Los grupos comunitarios del programa trabajan conjuntamente con las estructuras y actores del gobierno local",
"No sabe/ Información insuficiente para contestar.",
"El programa o sus grupos comunitarios y las estructuras y actores relevantes del gobierno local brindan información/mensajes contradictorios",
"El programa o sus grupos comunitarios y las estructuras y actores relevantes del gobierno local existentes no trabajan juntos en absoluto (incluso cuando están trabajando por los mismos objetivos)", 
"El programa o sus grupos comunitarios y las estructuras y los actores pertinentes del gobierno local colaboran a veces en algunas cuestiones",
"El programa, sus grupos comunitarios y las estructuras/actores del gobierno local colaboran regularmente y se complementan"],
p25:["H1. Los miembros de la comunidad supervisan las actividades clave y el progreso del programa",
"No sabe/ Información insuficiente para contestar.",
"No hay seguimiento participativo de la comunidad",
"El seguimiento comunitario es esporádico",
"El seguimiento comunitario se realiza con regularidad, pero es facilitado por el equipo a cargo del proyecto",
"El seguimiento comunitario se realiza con regularidad y es facilitado por miembros o estructuras de la comunidad"],
p26:["H2. Se lleva a cabo una evaluación participativa",
"No sabe/ Información insuficiente para contestar.",
"No hay ninguna instancia de evaluación participativa por parte de la comunidad",
"Los miembros de la comunidad participan en UNA o DOS de las siguientes actividades: 1) Planificación; 2) Recolección de datos; 3) Análisis; 4) Validación; 5) Conclusiones y recomendaciones; 6) Planificación de acciones",
"Los miembros de la comunidad participan en muchas (TRES o CUATRO) de estas actividades: 1) Planificación; 2) Recolección de datos; 3) Análisis; 4) Validación; 5) Conclusiones y recomendaciones; 6) Planificación de acciones",
"Los miembros de la comunidad son centrales en TODAS las actividades: 1) Planificación; 2) Recolección de datos; 3) Análisis; 4) Validación; 5) Conclusiones y recomendaciones; 6) Planificación de acciones."],
p27:["H3. Las actividades de monitoreo y evaluación examinan cómo el programa trabaja con - y beneficia- a diferentes grupos de personas incluyendo mujeres, personas con discapacidad, personas mayores y personas pertenecientes a minorías.",
"No sabe/ Información insuficiente para contestar.",
"Los miembros de la comunidad no saben porque no participan en el monitoreo y evaluación (M&E) O bien los miembros de la comunidad participan pero los sistemas de M&E no tienen en cuenta a los diferentes grupos de personas a la hora de recolectar o analizar la información",
"Las instancias de monitoreo y la evaluación recolectan y analizan información para comprender cómo el programa trabaja con - y beneficia- a algunos de los grupos de la comunidad (por ejemplo, hombres y mujeres, pero no personas con discapacidad)",
"Las instancias de monitoreo y la evaluación recolectan y analizan información para comprender de qué modo funciona el programa - y sus beneficios- para con la mayoría de los grupos de la comunidad",
"Las instancias de monitoreo y la evaluación recolectan y analizan información para comprender cómo y por qué el programa trabaja con todos los grupos de personas y los beneficia"],
p28:["I1. Quiénes facilitan deciden la hora, el lugar y el marco de las reuniones de modo tal que todos puedan participar en ellas",
"No sabe/ Información insuficiente para contestar.",
"Quiénes facilitan deciden la hora, el lugar y el marco de las reuniones en función de su propia conveniencia o la de unos pocos elegidos de la comunidad",
"Quiénes facilitan cumplen al menos con una de las siguientes condiciones: organizan las reuniones en un momento, lugar o entorno que permita a todas las personas participar y hablar libremente",
"Quiénes facilitan cumplen al menos dos de las siguientes condiciones: organizan las reuniones en un momento, lugar y entorno que permite a todas las personas participar y hablar libremente",
"Quiénes facilitan cumplen al menos tres de las siguientes condiciones:  organizan las reuniones en un momento, lugar y entorno que permite a todas las personas participar y hablar libremente"],
p29:["I2. Quiénes facilitan el proyecto son personas respetuosas y que fomentan el diálogo",
"No sabe/ Información insuficiente para contestar.",
"Quiénes facilitan dan lecciones y dicen a la gente lo que tiene que hacer, no escuchan y son irrespetuosos",
"Quiénes facilitan escuchan y tratan a la gente con respeto",
"Quiénes facilitan escuchan las ideas, tratan a la gente con respeto y animan a todos los participantes a hablar",
"Quiénes facilitan escuchan, tratan a la gente con respeto y animan a la gente a hablar entre sí"],
p30:["I3. Después de asistir a reuniones con quiénes facilitan, sentimos que:",
"No sabe/ Información insuficiente para contestar.",
"Fue una pérdida de tiempo; sólo asistimos porque tenemos que hacerlo",
"Escuchamos nuevas ideas, pero no estamos seguros de qué hacer con ellas",
"Escuchamos nuevas ideas y quiénes facilitan nos dicen qué hacer con ellas",
"Escuchamos nuevas ideas, recopilamos aprendizajes y decidimos colectivamente qué hacer con ellos"],
p31:["I4. (Sólo para facilitadores) Nos sentimos respaldados (recibimos formación periódica, entendemos lo que hacemos y por qué, disponemos de flexibilidad y presupuesto suficiente) por la organización ejecutora/agencia gubernamental para realizar nuestro trabajo",
"No sabe/ Información insuficiente para contestar.",
"La agencia gubernamental/organización que implementa la ejecución no hace ningún esfuerzo por apoyar nuestro trabajo",
"Recibimos apoyo en dos de estas áreas a) recibimos formación regularmente (no una sola vez) en nuestro idioma nativo, b) sabemos lo que estamos haciendo y por qué es importante, c) podemos cambiar el número de reuniones que facilitamos y su calendario para adaptarnos a las necesidades locales, d) la organización encargada de la ejecución nos proporciona espacios para las reuniones y todos los materiales para llevarlas a cabo, e) nuestra carga de trabajo es razonable (no se espera que cubramos demasiados pueblos o distancias muy largas ni que hagamos demasiadas reuniones)",
"Recibimos apoyo en tres de estas áreas a) recibimos formación regularmente (no una sola vez) en nuestro idioma nativo, b) sabemos lo que estamos haciendo y por qué es importante, c) podemos cambiar el número de reuniones que facilitamos y su calendario para adaptarnos a las necesidades locales, d) la organización encargada de la ejecución nos proporciona espacios para las reuniones y todos los materiales para llevarlas a cabo, e) nuestra carga de trabajo es razonable (no se espera que cubramos demasiados pueblos o distancias muy largas ni que hagamos demasiadas reuniones)",
"Recibimos apoyo en TODAS estas áreas a) recibimos formación regularmente (no una sola vez) en nuestro idioma nativo, b) sabemos lo que estamos haciendo y por qué es importante, c) podemos cambiar el número de reuniones que facilitamos y su calendario para adaptarnos a las necesidades locales, d) la organización encargada de la ejecución nos proporciona espacios para reuniones y todos los materiales para llevarlas a cabo, e) nuestra carga de trabajo es razonable (no se espera que cubramos demasiados pueblos o distancias muy largas ni que hagamos demasiadas reuniones)"]
}


