const basics={
    h1:"Información General",
    figure1:"Figura ",
    figure2:" de 5.  Da clic en las flechas para ver más resultados.",
    program:"Nombre del programa",
    organization:"Nombre de la organización (si es diferente del Nombre del programa)",
    orgtype:"Tipo de organización",
    country:"País o países en donde se llevó a cabo el programa (si aplica):",
    region:"Provincias o región/es (si corresponde):",
    name:"Name(s) completing this assessment",
    date:"Fecha de llenado de rúbrica:",
    stage:"Etapa de trabajo",
    save:"Guardar Datos",
    more:"Más Funciones",
    full:"Informe completo",
    clear:"Borrar datos",
    load: "Subir datos",
    comment:"Comentarios"
}
const downbutton="Haga clic aquí para descargar el archivo";
const sendmail="Para enviar por correo electrónico, adjunte el archivo descargado";
const stages=['piloto','proyecto nuevo','mediano plazo','fase final','terminado'];
const orgtypes=["Gobierno local/afiliado del gobierno","organización de la sociedad civil/sin fines de lucro"];
const comment="Comentarios adicionales y retroalimentación";
const clickto="Guardar comentarios";

const dimensions=[
"A: Participación, inclusión, voz",
"B: Recursos locales y conocimiento",
"C: Sostenibilidad",
"D: Mecanismos de rendición de cuentas",
"E: Sensibilidad a las dinámicas específicas del contexto",
"F: Colaboración al interior y entre comunidades",
"G: El DLCPG y su relación con los gobiernos subnacionales",
"H. Prácticas de monitoreo y evaluación que sustentan al DLCPG",
"I. Facilitación, inversión e intensidad de la iniciativa"];

const rubric={
p2:["A1. El programa garantiza la inclusión de todos los grupos de personas de la comunidad (como ancianos y jóvenes, hombres y mujeres, acomodados y pobres, de diferentes clanes, castas, religiones, etc.)",
"No sé / información insuficiente",
"El programa no tiene en cuenta los diferentes grupos de personas que viven en un pueblo",
"El programa tiene en cuenta a algunos grupos excluidos (no a todos) y garantiza su participación en las reuniones/actividades colectivas",
"El programa tiene en cuenta a la mayoría de los grupos de personas y garantiza su participación en las reuniones/actividades colectivas",
"El programa tiene en cuenta a todos los grupos de personas y garantiza su participación activa en las reuniones/actividades colectivas"],
p3:["A2. Los miembros de la comunidad deciden las prioridades del programa de CLD ANTES del diseño real del programa",
"No sabe/ información insuficiente",
"Los miembros de la comunidad no participan en la decisión de las prioridades del programa",
"Algunos miembros o grupos de la comunidad (p. ej., líderes tradicionales, terratenientes, etc.) participan en la decisión sobre las prioridades del programa",
"La mayoría de los grupos comunitarios participan en la decisión de las prioridades del programa",
"Todos los grupos de la comunidad participan en la decisión de las prioridades del programa y tienen la misma voz"],
p4:["A3. Los miembros de la comunidad desempeñan un papel activo en la planificación de los programas de CLD en su comunidad",
"No sabe/Información insuficiente",
"Los miembros de la comunidad no participan en el proceso de planificación",
"Algunos miembros o grupos de la comunidad (p. ej., líderes tradicionales, terratenientes, etc.) participan en el proceso de planificación",
"La mayoría de los grupos comunitarios participan en el proceso de planificación",
"Todos los grupos comunitarios participan en el proceso de planificación y tienen la misma voz en él."],
p5:["A4. Los órganos comunitarios que representan a todos los grupos y barrios ejecutan el programa.",
"No lo sé / información insuficiente",
"Las ONG o los líderes locales existentes implementan el programa",
"Las ONG y/o los líderes locales crean un organismo que implementará el programa o trabajan con un organismo existente que puede no incluir miembros de todos los grupos",
"Órganos con miembros autodesignados que representan a todos los grupos y barrios implementan el programa",
"Órganos elegidos que representan a todos los grupos y barrios implementan el programa"],
p6:["A5. El programa refuerza la voz y la confianza de los representantes de la comunidad para influir en la toma de decisiones",
"No sé/Información insuficiente",
"El programa no hace ningún esfuerzo para fomentar la voz o la confianza de los representantes de la comunidad",
"El programa fomenta la voz y la confianza de algunos representantes de la comunidad, pero no de los grupos excluidos",
"El programa fortalece la voz y la confianza de muchos representantes de la comunidad, incluidos los de algunos grupos excluidos",
"El programa refuerza la voz y la confianza de todos los representantes de la comunidad, incluidos los de todos los grupos excluidos"],
p7:["A6. El programa aumenta la concienciación sobre los derechos (sociales, económicos y políticos) y crea habilidades entre los representantes locales para pedir esos derechos",
"No sé/Información insuficiente",
"El programa no sensibiliza ni crea habilidades para pedir derechos",
"El programa sensibiliza sobre los derechos, pero no crea habilidades para pedirlos",
"El programa sensibiliza sobre los derechos y capacita a unas pocas personas para pedirlos",
"El programa sensibiliza sobre los derechos y se centra en capacitar a los representantes locales de todos los grupos para pedirlos"],
p8:["B1. El programa CLD se basa en los recursos y conocimientos locales",
"No sabe/Información insuficiente",
"El programa no tiene en cuenta los recursos y conocimientos locales",
"El programa explora los recursos locales, pero el personal de primera línea transmite los conocimientos externos",
"El programa utiliza los recursos locales y es consciente de los conocimientos locales",
"El programa utiliza y respeta los conocimientos y recursos locales"],
p9:["B2. La comunidad contribuye con sus recursos (por ejemplo, tiempo, dinero, mano de obra, tierra, materiales, etc.)",
"No sabe/Información insuficiente",
"Los miembros de la comunidad no contribuyen a la ejecución del programa en efectivo, especie o mano de obra",
"Los miembros de la comunidad contribuyen con tiempo/trabajo o recursos (tierra, dinero, materiales) porque es obligatorio",
"Los miembros de la comunidad contribuyen con tiempo/trabajo o recursos (tierra, efectivo, materiales), cuando se les anima",
"Los miembros de la comunidad deciden lo que se necesita, identifican voluntariamente recursos adicionales (tiempo/trabajo, tierra, efectivo, materiales) y los ofrecen voluntariamente"],
p10:["C1. Las comunidades son fundamentales en la planificación de cómo y cuándo debe completarse el programa y entregárseles a ellas",
"No sé/Información insuficiente",
"No existe un plan para la finalización y el traspaso del programa",
"La organización encargada de la ejecución elabora el plan de finalización y traspaso del programa y los líderes o miembros de la comunidad son informados al respecto",
"El plan de finalización y traspaso del programa se elabora en consulta con los líderes locales y los miembros de la comunidad",
"El plan para la finalización y el traspaso del programa está dirigido por los miembros de la comunidad y los líderes locales"],
p11:["C2. Las comunidades trabajan con las organizaciones ejecutoras para revisar y adaptar constantemente la planificación para el traspaso de programas y la transición",
"No sé/Información insuficiente",
"No existe ningún plan o estrategia para que su organización traspase los programas a la comunidad",
"Los planes para traspasar el programa a la comunidad sólo se hacen cuando el programa está llegando a su fin (o no queda financiación)",
"Los planes para traspasar el programa a la comunidad se elaboran al inicio del programa y se revisan al final del mismo o si se produce un contratiempo importante",
"Los planes para traspasar el programa a la comunidad se elaboran al inicio del programa y se revisan periódicamente con los miembros de la comunidad para reflejar la situación actual de la comunidad"],
p12:["C3. El programa garantiza que las estructuras comunitarias (como las organizaciones comunitarias o los grupos que ejecutan los programas) tengan la capacidad de seguir trabajando tras el traspaso",
"No sé / información insuficiente",
"El programa no hace ningún esfuerzo para garantizar la capacidad de las estructuras comunitarias para seguir trabajando después del traspaso",
"Existe un plan para el traspaso del programa, pero no una estrategia para garantizar que las estructuras comunitarias puedan seguir trabajando tras el traspaso y tengan la capacidad de obtener financiación/recursos (según sea necesario)",
"Existe una estrategia para garantizar que las estructuras comunitarias puedan seguir trabajando tras el traspaso, pero no hay actividades para desarrollar las capacidades para obtener financiación/recursos (según sea necesario)",
"El programa está implementando actividades para desarrollar capacidades que garanticen que las estructuras comunitarias puedan seguir trabajando tras el traspaso y obtener financiación/recursos (según sea necesario)"],
p13:["C4. Tras la finalización, el impacto del programa se mide con la participación local",
"No sé/Información insuficiente",
"No hay planes para medir el impacto del programa tras su finalización o la comunidad no sabe si hay planes",
"Hay planes para medir el impacto del programa (o se mide) tras su finalización. Los miembros de la comunidad están informados sobre el ejercicio y proporcionan información cuando se les solicita",
"Se mide el impacto (o está previsto medirlo) tras la finalización del programa y se consulta a los miembros de la comunidad en el ejercicio",
"El impacto se mide (o está previsto que se mida) tras la finalización del programa y los miembros de la comunidad participan activamente en todas las fases del ejercicio."],
p14:["C5. Tras el traspaso del programa a las estructuras comunitarias/del gobierno local, los miembros de la comunidad pertenecientes a todos los grupos (p. ej., mujeres, jóvenes, ancianos, pobres, personas con discapacidad, minorías) siguen beneficiándose de las actividades dirigidas por la comunidad.", 
"No lo sé / información insuficiente",
"Nadie obtiene ningún beneficio tras el traspaso del programa o sólo los grupos privilegiados siguen beneficiándose",
"El programa sigue beneficiando a algunos grupos incluso después del traspaso",
"El programa sigue beneficiando a la mayoría de los grupos incluso después del traspaso",
"El programa sigue beneficiando a todos los grupos incluso después del traspaso"],
p15:["D1. El programa y las estructuras comunitarias comparten información importante, por ejemplo, qué están haciendo, por qué, cómo y cómo se utilizaron los fondos",
"No sé/Información insuficiente",
"El programa no comparte ninguna información sobre lo que se está haciendo, cómo y por qué con la comunidad",
"El programa o los organismos comunitarios a veces comparten información básica sobre el programa, pero la mayoría de los detalles no están disponibles",
"El programa o los organismos comunitarios comparten a menudo información en torno al programa (la mayor parte de la información está disponible, pero no toda)",
"El programa y los organismos comunitarios comparten con regularidad información sobre fondos, procesos y actividades con los miembros de la comunidad e invitan a que se les envíen comentarios."],
p16:["D2. El programa aborda las quejas/reclamaciones de la comunidad",
"No sabe/ información insuficiente",
"El programa no dispone de ninguna vía para que los miembros de la comunidad presenten quejas o reclamaciones",
"El programa tiene una vía para que los miembros de la comunidad presenten quejas/reclamaciones, pero no es accesible ni fiable",
"El programa dispone de un medio accesible y fiable para que los miembros de la comunidad presenten quejas o reclamaciones, pero éstas no se abordan",
"El programa dispone de una vía accesible y fiable para que los miembros de la comunidad presenten quejas/reclamaciones, pero éstas se abordan"],
p17:["D3. Los resultados del seguimiento y la evaluación se comparten regularmente con los miembros de la comunidad",
"No sabe/Información insuficiente",
"Los resultados del seguimiento y la evaluación nunca se comparten con los miembros de la comunidad",
"Los resultados del seguimiento y la evaluación pueden ser compartidos con los miembros de la comunidad por las personas implicadas en el programa cuando lo consideran oportuno",
"Los resultados del seguimiento y la evaluación sólo se comparten con los miembros de la comunidad cuando surgen problemas",
"Los resultados del seguimiento y la evaluación se comparten regularmente con los miembros de la comunidad"],
p18:["E1. El programa responde a las necesidades y contextos cambiantes de la comunidad",
"No sabe/Información insuficiente",
"El programa no responde a las necesidades cambiantes de la comunidad (por ejemplo, inundaciones, sequías, hambre estacional, llegada de nuevas tecnologías, cambios en los sistemas políticos, etc.)",
"El programa es capaz de realizar algunos cambios",
"El programa es capaz de adaptarse según sea necesario a las necesidades cambiantes de la comunidad, incluidas las provocadas por crisis o catástrofes",
"El programa es capaz de adaptarse a las necesidades cambiantes de la comunidad, incluidas las provocadas por crisis o catástrofes, y crea mecanismos/estructuras para hacer frente a situaciones similares en el futuro"],
p19:["E2. El ritmo del programa CLD (es decir, el calendario, la frecuencia y la duración del compromiso con la comunidad) se determina con los miembros de la comunidad",
"No sabe/Información insuficiente",
"La comunidad no participa en la decisión del ritmo del programa",
"Se informa a la comunidad del ritmo del programa",
"Se consulta a algunos miembros de la comunidad para decidir el ritmo del programa",
"Se consulta a todos los miembros de la comunidad, incluidos los representantes de grupos marginados, para decidir el ritmo del programa"],
p20:["F1. El programa crea relaciones positivas entre ricos y pobres; pobres y pobres",
"No sabe/Información insuficiente",
"El programa no tiene en cuenta las diferencias económicas",
"El programa construye relaciones entre pobres y pobres",
"El programa involucra a ricos y pobres en discusiones y diálogos",
"El programa compromete a ricos y pobres a trabajar juntos para lograr un objetivo común"],
p21:["F2. El programa crea relaciones positivas dentro de los mismos grupos y entre los diferentes grupos étnicos, de casta, religiosos, etc.",
"No sabe/Información insuficiente",
"El programa no tiene en cuenta las diferencias de casta/etnia/religión",
"El programa crea relaciones entre personas de la misma casta/etnia/religión para que trabajen juntas por el cambio social",
"El programa involucra a personas de diferentes castas/etnias/religiones en debates y diálogos",
"El programa crea relaciones entre personas de diferentes castas/etnias/religiones para trabajar juntos por el cambio social"],
p22:["F3. El programa construye relaciones positivas entre mujeres y, entre hombres y mujeres",
"No sabe/Información insuficiente",
"El programa no trabaja con mujeres",
"El programa construye relaciones entre mujeres del mismo grupo",
"El programa construye relaciones entre todos los grupos de mujeres O entre mujeres y hombres",
"El programa construye relaciones entre todos los grupos de mujeres Y entre mujeres y hombres"],
p23:["F4. El programa vincula a las comunidades locales o a sus líderes con otros pueblos y sus líderes en distritos, provincias o estados",
"No sabe/Información insuficiente",
"El programa no construye redes y vínculos entre comunidades",
"El programa crea vínculos entre comunidades/líderes locales del mismo distrito",
"El programa crea vínculos entre comunidades/líderes locales de todo el distrito/estado/provincia/país",
"El programa crea vínculos entre comunidades a través de espacios estatales/regionales/nacionales para la acción colectiva"],
p24:["G1. Los grupos comunitarios del programa trabajan conjuntamente con las estructuras y actores del gobierno local",
"No sabe/Información insuficiente",
"El programa o sus grupos comunitarios y las estructuras y actores relevantes del gobierno local dan información/mensajes contradictorios",
"El programa o sus grupos comunitarios y las estructuras y actores relevantes del gobierno local existentes no trabajan juntos en absoluto (incluso cuando están trabajando por los mismos objetivos)", "El programa o sus grupos comunitarios y las estructuras y actores relevantes del gobierno local existentes no trabajan juntos en absoluto (incluso cuando están trabajando por los mismos objetivos)",
"El programa o sus grupos comunitarios y las estructuras y los actores pertinentes del gobierno local colaboran a veces en algunas cuestiones",
"El programa y sus grupos comunitarios y estructuras/actores del gobierno local colaboran regularmente y se complementan"],
p25:["H1. Los miembros de la comunidad supervisan las actividades clave y el progreso del programa",
"No sabe/ información insuficiente",
"No hay seguimiento participativo de la comunidad",
"El seguimiento comunitario se realiza a veces",
"El seguimiento comunitario se realiza con regularidad, pero lo facilita el personal de primera línea",
"El seguimiento comunitario se realiza con regularidad y está facilitado por miembros o estructuras de la comunidad"],
p26:["H2. Se lleva a cabo una evaluación participativa",
"No lo sé / información insuficiente",
"No hay evaluación participativa de la comunidad",
"Los miembros de la comunidad participan en UNA o DOS de estas actividades: 1) Planificación; 2) Recogida de datos; 3) Análisis; 4) Validación; 5) Conclusiones y recomendaciones; 6) Planificación de acciones",
"Los miembros de la comunidad participan en muchas (TRES o CUATRO) de estas actividades: 1) Planificación; 2) Recogida de datos; 3) Análisis; 4) Validación; 5) Conclusiones y recomendaciones; 6) Planificación de la acción",
"Los miembros de la comunidad son fundamentales en TODAS las actividades: 1) Planificación; 2) Recogida de datos; 3) Análisis; 4) Validación; 5) Conclusiones y recomendación; 6) Planificación de la acción."],
p27:["H3. Las actividades de seguimiento y evaluación examinan cómo el programa trabaja con diferentes grupos de personas y cómo les beneficia, incluidas las mujeres, las personas con discapacidad, las personas mayores y las personas pertenecientes a minorías",
"No lo sé/Información insuficiente",
"Los miembros de la comunidad no lo saben porque no participan en el seguimiento y la evaluación (S&E) O los miembros de la comunidad participan pero los sistemas de S&E no tienen en cuenta a los diferentes grupos de personas a la hora de recopilar o analizar la información",
"El seguimiento y la evaluación recopilan y analizan la información para comprender cómo funciona el programa con algunos de los grupos de la comunidad y cómo les beneficia (por ejemplo, hombres y mujeres, pero no personas con discapacidad)",
"El seguimiento y la evaluación recopilan y analizan información para comprender cómo funciona el programa con la mayoría de los grupos de la comunidad y cómo les beneficia",
"El seguimiento y la evaluación recopilan y analizan información para comprender cómo y por qué el programa trabaja con todos los diferentes grupos de personas y les beneficia"],
p28:["I1. Los facilitadores deciden la hora, el lugar y el marco de las reuniones para que todos puedan participar en ellas.", 
"No sabe/Información insuficiente",
"Los facilitadores deciden la hora, el lugar y el marco de las reuniones en función de su propia conveniencia o la de unos pocos elegidos de la comunidad",
"Los facilitadores cumplen al menos una de las siguientes condiciones: organizan las reuniones en un momento, lugar o entorno que permita a todas las personas participar y hablar libremente",
"Los facilitadores cumplen al menos dos de las siguientes condiciones: organizan las reuniones en un momento, lugar y entorno que permite a todas las personas participar y hablar libremente",
"Los facilitadores cumplen las tres condiciones siguientes: organizan las reuniones en un momento, lugar y entorno que permiten a todas las personas participar y hablar libremente"],
p29:["I2. Los facilitadores del proyecto son respetuosos y fomentan el diálogo",
"No sé/Información insuficiente",
"Los facilitadores sermonean y dicen a la gente lo que tiene que hacer, no escuchan y son irrespetuosos",
"Los facilitadores escuchan y tratan a la gente con respeto",
"Los facilitadores escuchan las ideas, tratan a la gente con respeto y animan a todos los participantes a hablar",
"Los facilitadores escuchan, tratan a la gente con respeto y animan a la gente a hablar entre sí"],
p30:["I3. Después de asistir a las reuniones con los facilitadores, sentimos:",
"No sé/ información insuficiente",
"Fue una pérdida de tiempo; sólo asistimos porque tenemos que hacerlo",
"Escuchamos nuevas ideas pero no estamos seguros de qué hacer con ellas",
"Escuchamos nuevas ideas y los facilitadores nos dicen cómo actuar con ellas",
"Escuchamos nuevas ideas y aprendizajes y decidimos colectivamente cómo actuar con ellos"],
p31:["I4. (Sólo para facilitadores) Nos sentimos apoyados (recibimos formación periódica, entendemos lo que hacemos y por qué, tenemos flexibilidad y presupuestos) por la organización implementadora/organismo gubernamental para hacer nuestro trabajo",
"No lo sé / información insuficiente",
"La organización/agencia gubernamental encargada de la ejecución no hace ningún esfuerzo por apoyar nuestro trabajo",
"Recibimos apoyo en dos de estas áreas a) recibimos formación regularmente (no una sola vez) en nuestro idioma local, b) sabemos lo que estamos haciendo y por qué es importante, c) podemos cambiar el número de reuniones que facilitamos y su calendario para adaptarnos a las necesidades locales, d) la organización encargada de la ejecución nos proporciona espacios para las reuniones y todos los materiales para llevarlas a cabo, e) nuestra carga de trabajo es razonable (no se espera que cubramos demasiados pueblos o distancias muy largas ni que hagamos demasiadas reuniones)",
"Recibimos apoyo en tres de estas áreas a) recibimos formación con regularidad (no una sola vez) en nuestro idioma local, b) sabemos lo que estamos haciendo y por qué es importante, c) podemos cambiar el número de reuniones que facilitamos y su calendario para adaptarnos a las necesidades locales, d) la organización encargada de la ejecución nos proporciona espacios para las reuniones y todos los materiales para llevarlas a cabo, e) nuestra carga de trabajo es razonable (no se espera que cubramos demasiados pueblos o distancias muy largas ni que hagamos demasiadas reuniones)",
"Recibimos apoyo en TODAS estas áreas a) recibimos formación regularmente (no una sola vez) en nuestro idioma local, b) sabemos lo que estamos haciendo y por qué es importante, c) podemos cambiar el número de reuniones que facilitamos y su calendario para adaptarnos a las necesidades locales, d) la organización encargada de la ejecución nos proporciona espacios para reuniones y todos los materiales para llevarlas a cabo, e) nuestra carga de trabajo es razonable (no se espera que cubramos demasiados pueblos o distancias muy largas ni que hagamos demasiadas reuniones)"]
}