
﻿const basics={  
    figure1:"Ennamba ",  
    figure2:" ku 5. Koona ku bufumu okulaba ebisingawo.",
     h1:"Ebikwata ku pulogulaamu",
    program:"Erinnya lya pulogulaamu", 
    organization:"Erinnya ly'ekitongole", 
    orgtype:"Ekiti ekitongole mwe kigwa:", 
    country:"Ensi Pulogulaamu mweddukanyizibwa ", 
    region:"Ekitundu Pulogulaamu mweri (bwe kiba kyeetagisa)", 
    name:"Erinnya ly'omuntu/abantu abamaliriza omulimu gw'okupima", 
    date:"Ennaku z'omwezi kwe mumalidde", 
    stage:"Omutendera", 
    save:"Tereka ebikunganyiziddwa",  
    more:"Emirimu Emirala",
    full:"Alipoota mu bujjuvu",
    clear:"Okulongoosa Data",
    load:"Teeka Data",
    comment:"Baako ky'oyogera" 
    }
    const stages=['pilot','new','midterm','mature','complete']; 
    const orgtypes=["Gavumenti ey'ekitundu/gavumenti gye mukwatagana nayo","Ekibiina/ekitongole ky'obwa nakyewa"]; 
    const clickto="Nyiga okusobola okutereka ky'oyogedde ku Pulogulaamu";
    const comment="ky'olowooza"; 
    const dimensions=[
    "A: Okwetabamu, buli muntu okwenyigiramu, na kiki kye bagamba", 
    "B: Ebikozesebwa n'amagezi eby'omu kitundu", 
    "C: Obuwangaazi bwa pulogulaamu n'okugizza mu mikono gy'abantu abalala", 
    "D: Amakubo ag'okupima ebikoleddwa.", 
    "E: Engeri abantu gye bategeeramu Pulogulaamu", 
    "F: Okukolagana",
    "G: okukolagana ne gavumenti ey'ekitundu/ekibiina ky'obwa nakyewa", 
    "H. Ebikolebwa mu kulondoola n'okupima Pulogulaamu", 
    "I. Okuvujjirira"]; 
    
    const rubric={
    p2:["A1. Pulogulaamu efuba okulaba nga buli muntu mu kitundu yetabamu (okugeza abakadde n'abato, abaami n'abakyala, abali obulungi n'abali obubi, okuva mu bika eby'enjawulo, ebibinja eby'ejawulo, eddiini n'ebirala.)",
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Pulogulaamu tefaayo ku bantu abali mu guluupu ez'enjawulo ku kyalo.", 
    "Pulogulaamu efaayo ku guluupu ezirekeddwa emabega (si zonna) era n'efuba okulaba nga beetaba mu nkiiko/n'ebintu ebigattira awamu abantu", 
    "Pulogulaamu efaayo ku guluupu z'abantu ezisinga obungi era n'efuba okulaba nga beetaba mu nkiiko/n'ebintu ebirala ebigattira awamu abantu.", 
    "Pulogulaamu efaayo ku guluupu z'abantu bonna mu kitundu era n'efuba okulaba nga beetaba mu nkiiko/n'ebintu ebirala ebigattira abantu awamu."],
    p3:["A2. Abantu b'omu kitundu be basalawo ku birina okusoosowazibwa mu pulogulaamu ya CLD (Pulogulaamu ereeta abantu ku mwanjo ne beetaba mu nteekateeka z'okugoba obwavu) nga enteekateeka ya Pulogulaamu entuufu tennaba kubagibwa.", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Abantu b'omu kitundu tebeetaba mu kusalawo mu kusalawo ebirina okusoosowazibwa mu Pulogulaamu", 
    "Bammemba b'omu kitundu abamu (okugeza abakulembeze ab'ebyobuwangwa, Bannanyini ttaka, n'abalala) oba guluupu ezimu, zeetaba mu kusalawo ebirina okusoosowazibwa mu Pulogulaamu.", 
    "Guluupu z'omu kitundu ezisinga zeetaba mu kusalawo ebirina okusoosowazibwa mu Pulogulaamu", 
    "Guluupu z'omu kitundu zonna zeetaba mu kusalawo ebirina okusoosowazibwa mu pulogulaamu era zirina eddoboozi lya kyenkanyi."],
    p4:["A3. Bammemba b'omu kitundu bakola obuvunanyizibwa bwa maanyi mu kutegeka Pulogulaamu ya CLD ey'okwekulaakulanya mu kitundu kyabwe.", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Bammemba b'omu kitundu tebeetaba mu mu mutendera gwa kuteekateeka.", 
    "Bammemba b'omu kitundu abamu (okugeza abakulembeze ab'ebyobuwangwa, Bannanyini ttaka, n'abalala) oba guluupu ezimu, zeetaba mu mutendera gw'okusalawo.", 
    "Guluupu z'omu kitundu ezisinga zeetaba mu mutendera gw'okuteekateeka", 
    "Guluupu z'abantu zonna mu kitundu zeetaba mu mutendera gw'okuteekateeka era zirina eddoboozi lya kyenkanyi mu mutendera guno."],
    p5:["A4. Ebibiina/Ebitongole by'omu kitundu ebikiikirira guluupu z'abantu zonna mu kitundu ekiba kikolebwamu n'emiriraano, be bateeka pulogulaamu mu nkola", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Ebitongole by'obwa nakyewa oba abakulembeze mu kitundu be bateeka Pulogulaamu mu nkola", 
    "Ebibiina by'obwa nakyewa n'abakulembeze b'omu kitundu beekolamu olukiiko olunateekanga mu nkola pulogulaamu oba okukolagana n'olukiiko lwe banasangawo oluyinza obutabeerako bammemba bonna okuva mu guluupu ez'enjawulo.", 
    "Enkiiko eziriko bammemba abesowolayo ku lwabwe nga bakiikirira ebibiina byonna mu kitundu n'emiriraano bateeka pulogulaamu mu nkola.", 
    "Obukiiko obulondeddwa abantu nga nga bukiikirira guluupu zonna mu kitundu n'emiriraano, buteeka Pulogulaamu mu nkola."],
    p6:["A5. Pulogulaamu ezimba eddoboozi n'okwekiririzaamu mu bakiise, okusobola okukola okusalawo okulungi.", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Pulogulaamu Terina kyekolawo okuzimba eddoboozi n'okwekiririzaamu mu bakiise b'ababantu mu kitundu", 
    "Pulogulaamu ezimba eddoboozi n'okwekiririzaamu mu bakiise b'abantu, naye okugyako aba guluupu ezalekebwa ebbali.", 
    "Pulogulaamu ezimba eddoboozi n'okwekkiririzaamu mu bakiise b'abantu omuli n'abo abava mu guluupu ezimu ezalekebwa ebbali.", 
    " Pulogulaamu ezimba eddoboozi n'okwekkiririzaamu mu bakiise b'abantu omuli n'abo abava mu guluupu zonna ezalekebwa ebbali.",],
    p7:["A6. Pulogulaamu estumbula okumanyisibwa ku ddembe ly'omuntu (mu mbeera eza bulijjo, mu by'enfuna n'ebyobufuzi era ewa abakiise b'abantu obukugu okubanja eddembe eryo.", "Obutamanya/okumanya eby'olumaggamagga", 
    "Pulogulaamu teriimu kumanyisa abantu era n'obukugu okubanja eddembe tebuzimbibwa.", "Pulogulaamu etumbula okumanyisa abantu eddembe lyabwe, naye tezimba bukugu mu bantu kusobola kubanja ddembe lyabwe.", 
    "Pulogulaamu emanyisa abantu eddembe lyabwe era n'ezimba abantu abatono abasobola okulibanja.", 
    "Pulogulaamu erimu okumanyisa abantu, era essira eriteeka ku kuzimba obukugu mu bakiise okuva mu guluupu zonna okusobola okulibanja."],
    p8:["B1. Pulogulaamu ya CLD ezimbira ku magezi n'ebintu by'omukitundu.", "Obutamanya/okumanya eby'olumaggamagga", 
    "Pulogulaamu tefaayo ku kukozesa magezi na bintu bya mu kitundu.", 
    "Pulogulaamu ekozesa bulungi amagezi n'ebintu by'omu kitundu. Wabula yesigama nnyo mu magezi agava ebweru nga gaweerezebwa abakozi baabwe abasookerwako.", 
    "Pulogulaamu ekozesa amagezi n'ebintu by'omu kitundu bweraba nga kyetaagisa.", "Pulogulaamu ekozesa era essa ekitiibwa mu magezi n'ebintu by'omu kitundu. Ezimbiddwa ku bintu bino."],
    p9:["B2. Abantu mu kitundu bawaayo ebintu byabwe (okugeza Obudde, ssente, abakozi, ettaka, ebikozesebwa, n'okumanyika kwabwe.)", 
    " Obutamanya/okumanya eby'olumaggamagga", 
    "Abantu tebalina kye bawaayo eri pulogulaamu okugiteeka mu nkola, mu bya ssente, ettaka, n'abakozi.", 
    "Abantu bawaayo obudde/okwenyigira mu mirimu oba okuwaayo ebirala (ettaka, ssente, ebikozesebwa ebirala) kubanga kya tteeka.", 
    "Abantu b'omu kitundu bawaayo obudde/okwenyigira mu mirimu oba okuwaayo ettaka, ssente, n'ebikozesebwa ebirala, bwe baba bakubiriziddwa.", 
    "Abantu basalawo ebiba byetaagisa, era ne babiwaayo (omuli obudde/okwenyigira mu mirimu, ettaka, ssente, n'ebikozesebwa ebirala)"],
    p10:["C1. Abantu b'omu kitundu bali wakati mu kukola pulaani/enteekateeka ku ngeri na ddi pulogulaamu wenakomekkerezebwa n'ebakwasibwa mu butongole.", 
    "Obutamanya/okumanya eby'olumaggamagga",  
    "Tewali pulaani/nteekateeka yakumaliriza Pulogulaamu n'okugikwasa abatuuze", 
    "Pulaani y'okumaliriza pulojekiti n'okugiwaayo etondebwawo ekitongole ekigiteeka mu nkola n'abakulembeze b'ekitundu  oba okugibuulirako ku batuuze.", 
    "Pulaani/enteekateeka y'okumaliriza Pulogulaamu n'okugiwaayo ebangibwawo wakati mu kwebuuza ku bakulembeze b'omu kitundu n'abatuuze", 
    "Pulaani/enteekateeka y'okumaliriza pulogulaamu n'okugiwaayo, ekulemberwamu abatuuze n'abakulembeze b'ekitundu."],
    p11:["C2. Abantu bakolagana n'ebitongole ebiteeka mu nkola pulogulaamu okubeera nga betegereza n'okutegeera pulaani/enteekateeka y'okumaliriza Pulogulaamu n'okugiwaayi eri abatuuze",  
    "Obutamanya/okumanya eby'olumaggamagga ", 
    "Tewali pulaani yonna oba nteekateeka ya kitongole okuwaayo Pulogulaamu eri abatuuze.", "Pulaani/enteekateeka ez'okuwaayo Pulogulaamu eri abatuuze zikolebwa mu kiseera nga Pulogulaamu egenda kukomekkerezebwa (oba nga tewakyali ssente)", 
    "Pulaani/enteekateeka ez'okuwaayo Pulogulaamu eri abantu zikolebwa ku ntandikwa ya Pulogulaamu era ne ziddibwamu okwekenenyezebwa ku nkomerero ya Pulogulaamu oba nga waliwo okugootanyizibwa okw'amaanyi", 
    "Pulaani/enteekateeka ez'okuwaayo pulogulaamu eri abantu zikolebwa ku ntandikwa ya pulogulaamu era ne ziddamu okwekenenyezebwa wamu n'abatuuze okusobola okutuukana n'embeera eriwo mu kitundu"],
    p12:["C3. Pulogulaamu efuba okulaba nga empagi z'omu kitundu okugeza (okugeza ebibiina byobwa nakyewa, Guluupu eziteeka Pulogulaamu mu nkola) ziba n'obusobozi okugenda maaso nga emirimu gitambula nga Pulogulaamu emaze okukwasibwa abatuuze.", 
    "Obutamanya/okumanya eby'olumaggamagga ", 
    "Pulogulaamu Terina ky'ekolawo okulaba nga ezimba obusobozi mu mpagi/ebitongole by'omu kitundu okusobola okutambuza emirimu nga Pulogulaamu emaze okuweebwayo eri abantu.", 
    "Pulaani ey'okuwaayo Pulogulaamu eri abantu weeri, naye tewali nteekateeka ya kuzimba mpagi ez'omu kitundu, pulogulaamu kwerina okutambulira emirimu okusigala nga gitambula oluvanyuma lw'okugikwasa abantu, n'okufuna obuyambi bwa ssente obuba bwetaagibwa.", 
    "Waliwo Pulaani ey'okulaba nga empagi z'omu kitundu zisigala nga zikola bulungi oluvanyuma lw'okuwaayo Pulogulaamu naye tewali bikolebwa okulaba nga pulojekiti esigala evvujjirirwa nga bweba yetaaga.", 
    "Pulogulaamu eteeka mu nkola emirimu egy'enjawulo okuzimba obusobozi okulaba nga empagi z'omu kitundu zisigala zitambuza emirimu era nga zifina ssente ezeetaagisa oluvanyuma lw'okuweebwayo eri abantu."],
    p13:["C4. Nga Pulogulaamu ewedde, amaanyi gaayo gajja kupimibwa ku ngeri abatuuze gye beetabamu.", 
    " Obutamanya/okumanya eby'olumaggamagga" , 
    "Tewali Pulaani yonna ya kupima maanyi ga Pulogulaamu ng'emaze okukomekkerezebwa oba abantu tebamanyi oba waliwo Pulaani yonna.", 
    "Waliwo Pulaani ey'okupima amaanyi ga Pulogulaamu mu kitundu, oba epimibwa emaze kumalirizibwa. Abatuuze bategeezebwa ku bikolebwa era baddamu ebibabuuziddwa nga bwe biba bisabiddwa.", 
    "Amaanyi ga Pulogulaamu oba enkyukakyuka gy'ekoze epimibwa (oba eteekebwateekebwa okupimibwa) nga Pulogulaamu ekomekkerezeddwa era abatuuze beebuzibwako mu nteekateeka eno.", 
    " Amaanyi ga Pulogulaamu oba enkyukakyuka gy'ekoze epimibwa (oba eteekebwateekebwa okupimibwa) nga Pulogulaamu ekomekkerezeddwa era abatuuze beetabamu ku buli mutendera ng'ekolebwa."],
    p14:["C5. Nga pulogulaamu emaze okuweebwa abantu/gavumenti ez'ebitundu, abatuuze okuva mu guluupu zonna (okugeza Abakazi, Abavubuka, Abakadde, Abaavu, abaliko obulemu, n'abantu abakkiririza mu kintu naye nga batono) basigala baganyulwa mu mirimu gya Pulogulaamu.", 
    " Obutamanya/okumanya eby'olumaggamagga ",  
    "Tewali muntu n'omu aganyulwa mu pulogulaamu ng'emaze okuwebwayo eri abantu oba abantu ab'olubatu ne guluupu entono ze zisigala ziganyulwa.", 
    "Pulogulaamu egenda maaso n'okuganyula guluupu ezimu, ng'emaze okuwebwayo eri abantu.", "Pulogulaamu egenda mu maaso n'okuganyula guluupu ezisinga ne bweba ng'emaze okuwebwayo eri abantu.", 
    "Pulogulaamu egenda mu maaso n'okuganyula guluupu zonna naddala ezo ezisinga okuba obubi, ne bweba emaze okuwebwayo eri abantu."],
    p15:["D1. Pulogulaamu n'ebibiina n'abakulembeze abagiddukanya bagabana amagezi ag'omugaso okugeza biki bye bakola, lwaki, ngeri ki, n'engeri ssente gye zaakozesebwa.", 
    " Obutamanya/okumanya eby'olumaggamagga ",  
    "Pulogulaamu tegaba mawulire na batuuze ku bikolebwa, lwaki bikolebwa, era bikolebwa mu ngeri ki.", 
    "Pulogulaamu oba abagiddukanya ebiseera ebimu bagaba amawulire amangungu agakwata ku pulogulaamu naye ebisingawo babyesigaliza", 
    "Pulogulaamu oba abagiddukanya bagaba ebikwata ku pulogulaamu (ebisinga naye amawulire gonna tegabaawo).", 
    "Pulogulaamu n'abagiddukanya bagaba nnyo amawulire eri abatuuze agakwata ku ssente, emitendera, n'emirimu egikolebwa era baaniriza ebirowoozo ebiva mu bantu."],
    p16:["D2. Pulogulaamu ekola ku kwemulugunya kw'abantu n'ebizibu byabwe.", 
    " Obutamanya/okumanya eby'olumaggamagga ",  
    "Pulogulaamu Terina muwaatwa gwonna abatuuze mwe basinziira kuwaayo kwemulugunya kwabwe.", 
    "Pulogulaamu erina engeri ewa abatuuze omwaganya okwemulugunya naye si nyangu oba teyesigika.", 
    "Pulogulaamu erina enkola enyangu era eyesigika mu kuwaayo okwemulugunya, naye okwmulugunya kw'abantu tekukolwako.", 
    "Pulogulaamu erina amakubo n'emiwaatwa egyesigika abatuuze mwe bayita okuwaayo okwemulugunya era okwemulugunya okwo kukolebwako."],
    p17:["D3. Ebivudde mu kulondoola n'okupima engeri enkola ya pulogulaamu bibuulirwa abatuuze buli kiseera.", 
    " Obutamanya/okumanya eby'olumaggamagga ", 
    "Ebiva mu kunonyereza, okulondoola n'okupima enkola ya Pulogulaamu tebabibuulira batuuze.", 
    "Ebiva mu kulondoola n'okupima enkola ya Pulogulaamu abagiddukanya bayinza okubigabanako n'abatuuze singa baba baagadde. " , 
    "Ebivudde mu kulondoola n'okupima enkola ya Pulogulaamu bibuulirwa abatuuze mu mbeera nga waliwo ebizibu ebizze.", 
    "Ebiva mu kunonyereza n'okupima bibuulirwa abatuuze buli kiseera."],
    p18:["E1. Pulogulaamu egenderera okukyusa abatuuze n'ebyetaago byabwe n'embeera mwe bawangaalira.", 
    " Obutamanya/okumanya eby'olumaggamagga ",  
    "Pulogulaamu tefaayo ku byetaago bya kitundu okusobola okubikyusa (eky'okulabirako, amataba, ekyeya, enjala, okujja kwa tekinologiya omupya, enkyukakyuka mu by'obufuzi n'ebirala)", 
    "Pulogulaamu esobola okubaako by'ekyusa.", 
    "Pulogulaamu esobola esobola okukyusa ebyetaago by'abantu omuli n'ebyo ebireeteddwa, akatyabaga oba ebibamba.", 
    " Pulogulaamu esobola esobola okukyusa ebyetaago by'abantu omuli n'ebyo ebireeteddwa, akatyabaga oba ebibamba era n'ezimba amakubo n'empagi ebisobola okukola ku bizibu bino mu maaso."],
    p19:["E2. Emisinde Pulogulaamu kwetambulira (Okugeza, Obudde, emirundi, n'obuwanvu bw'okwogerezeganya n'abantu) esalwawo batuuze.", 
    " Obutamanya/okumanya eby'olumaggamagga", 
    "Abatuuze tebeetaba mu kusalawo misinde pulogulaamu kwetambulira.", 
    "Abatuuze bababuulira emisinde pulogulaamu kweddukira.", 
    "Abatuuze abamu beebuzibwako mu kusalawo emisinde pulogulaamu kwetambulira.", "Abatuuze bonna mu kitundu beebuzibwako, omuli n'abakiikirira guluupu ezisosolwa ennyo n'okulekebwa emabega mu kusalawo emisinde Pulogulaamu kwetambulira."],
    p20:["F1. Pulogulaamu ezimba enkolagana ennungi wakati wa guluupu ez'enjawulo okusinziira ku byenfuna - wakati w'abagagga n'abaavu; n'abaavu n'abaavu.",
    " Obutamanya/okumanya eby'olumaggamagga ", 
    "Pulogulaamu tefaayo ku njawulo y'abantu mu byenfuna.", 
    "Pulogulaamu ezimba enkolagana wakati w'abaavu n'abaavu.", 
    "Pulogulaamu eteekawo okwogerezeganya wakati w'abaavu n'abagagga.", 
    "Pulogulaamu eteekawo embeera ng'abagagga n'abaavu bakolera wamu okutuukiriza ekigendererwa eky'awamu."],
    p21:["F2. Pulogulaamu ezimba enkolagana ennungi mu guluupu ez'enjawulo, n'ebintu ebyawula abantu, omuli amawanga, enjawulo mu buzaale bw'abantu, eddiini n'ebirala.", 
    " Obutamanya/okumanya eby'olumaggamagga", 
    "Pulogulaamu tesosola era tefaayo ku njawulo y'abantu mu mawanga, eddiini n'obuzaale.", "Pulogulaamu ezimba enkolagana wakati w'abantu abafaanaganya obuzaale, amawanga, n'eddiini okusobola okukolera awamu okuleetawo enjawulo mu bantu.", 
    "Pulogulaamu eteekawo embeera esobozesa abantu abalina enjawulo mu buzaale, amawanga n'eddiini okwogerezeganya n'okukubaganya ebirowoozo.", 
    "Pulogulaamu ezimba enkolagana mu bantu bonna, ab'obuzaale, amawanga n'eddiini eby'enjawulo okusobola okukolaganira awamu okukyusa embeera y'abantu."],
    p22:["F3. Pulogulaamu ezimba enkolagana ennungi wakati w'abantu ab'ekikula eky'enjawulo - abakazi n'abakazi, n'abakazi n'abasajja.", 
    " Obutamanya/okumanya eby'olumaggamagga ", 
    "Pulogulaamu tekola na bakazi.", 
    "Pulogulaamu ezimba enkolagana wakati w'abakazi okuva mu guluupu emu.", 
    "Pulogulaamu ezimba enkolagana wakati wa guluupu zonna ez'abakazi oba wakati w'abakazi n'abasajja.", 
    "Pulogulaamu ezimba enkolagana wakati wa guluupu zonna ez'abakazi oba wakati w'abakazi n'abasajja ERA (wekyetaagisa) wakati w'abakazi ne guluupu ez'abantu ab'ekikula ekirala."],
    p23:["F4. Pulogulaamu egatta abatuuze oba abakulembeze baabwe ku byalo ebirala, ate abakulembeze baabwe basukka awo ne bayungibwa ku disitulikiti, amabendobendo, n'ensi endala", 
    "Obutamanya/okumanya eby'olumaggamagga",
    "Pulogulaamu tezimba muyungagano wakati wa bitundu eby'enjawulo.", 
    "Pulogulaamu ezimba enkwatagana wakati w'ebitundu/abakulembeze baabyo okuva mu disitulikiti emu.", 
    "Pulogulaamu ezimba enkwatagana wakati w'ebyalo,/abakulembeze b'ebitundu mu disitulikiti ez'enjawulo/ensi/ amabendobendo/n'amawanga.", 
    "Pulogulaamu ezimba enkwatagana wakati w'ebitundu/amawanga/amabendobendo/ okusobola okutuukiriza ekigendererwa ekimu n'okukolaganira awamu."],
    p24:["G1. Guluupu z'omu kitundu ez'enyigira mu Pulogulaamu zikolaganira wamu n'obukulembeze bwa gavumenti ez'ebitundu n'abali mu mulimu guno abalala.", 
    " Obutamanya/okumanya eby'olumaggamagga" , 
    "Pulogulaamu oba guluupu z'abantu ku byalo n'obukulembeze bwa gavumenti ez'ebitundu obuliko n'abali mu mulimu guno abalala, bakubagana empawa ku mawulire ge bafulumya.", 
    " Pulogulaamu oba guluupu z'abantu ku byalo n'obukulembeze bwa gavumenti ez'ebitundu obuliko, n'abali mu mulimu guno abalala, tebakolera wamu (ne bwe baba bakolerera ebigendererwa bye bimu).", 
    " Pulogulaamu oba guluupu z'abantu ku byalo n'obukulembeze bwa gavumenti ez'ebitundu obuliko n'abali mu mulimu guno abalala, ebiseera ebimu bakolaganira wamu ku nsonga ezimu.", " Pulogulaamu oba guluupu z'abantu ku byalo n'obukulembeze bwa gavumenti ez'ebitundu obuliko n'abali mu mulimu guno abalala, bakolaganira wamu ekiseera kyonna era bayambagana."],
    p25:["H1. Abatuuze balondoola emirimu egy'enkizo engeri gye gitambulamu mu Pulogulaamu.", 
    " Obutamanya/okumanya eby'olumaggamagga" , 
    "Abatuuze tebenyigiramu wadde n'akamu mu kulondoola emirimu gya Pulogulaamu", 
    "Olumu abatuuze balondoola ebikolebwa Pulogulaamu.", 
    "Abatuuze balambula nnyo emirimu egikolebwa pulogulaamu, naye bavujjirirwa Pulogulaamu oba abakozi b;ekitongole.", 
    " Abatuuze balambula nnyo emirimu egikolebwa pulogulaamu, era bavujjirirwa batuuze bannaabwe oba obukulembeze obulala."],
    p26:["H2. Abatuuze benyigira mu kupima Pulogulaamu wetuuse.", 
    " Obutamanya/okumanya eby'olumaggamagga", 
    "Abatuuze tebeetaba mu kupima mirimu gya pulogulaamu.", 
    "Abatuuze benyigira mu mulimu GUMU oba EBIRI egy'okupima Pulogulaamu: 1) Okuteekateeka; 2) Okukungaanya ebikwata ku pulogulaamu/abantu; 3) Okusengejja; 4) Okuzza obuggya; 5) Okufundikira n'okuwa amagezi; 6) Okuteekateeka eby'okukola.", 
    "Abatuuze benyigira mu mirimu egiwerako (ESATU oba ENA) : 1) Okuteekateeka; 2) Okukungaaya ebikwta ku pulogulaamu/abantu; 3) Okusengejja; 4) Okuzza obuggya; 5) Okufundikira n'okuwa amagezi; 6) Okuteekateeka eby'okukola.", 
    "Abatuuze basaale mu mirimu gino gyonna: 1) Okuteekateeka; 2) Okukungaaya ebikwta ku pulogulaamu/abantu; 3) Okusengejja; 4) Okuzza obuggya; 5) Okufundikira n'okuwa amagezi; 6) Okuteekateeka eby'okukola.",],
    p27:["H3. Emirimu gy'okulondoola n'okupima gitunuulira engeri Pulogulaamu gy'etambuzibwamu n'okulaba oba eganyula abantu ab'enjawulo omuli abakazi, abaliko obulemu, abakadde, abantu abatono, n'abagwira.", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Abatuuze tebamanyi kubanga tebenyigira mu mirimu gya kulondoola na kupima OBA abatuuze benyigiramu naye enkola gye bakozesa okulondoola teyogera ku guluupu z'abantu ab'enjawulo nga bakola okunonyereza.",
    "Okulondoola n'okupima kukungaanya era ne kusengejja engeri Pulogulaamu gy'etambulamu n'engeri guluupu z'abantu ez'enjawulo gye ziganyulwamu (Okugeza Abasajja n'abakazi, naye si abaliko obulemu).", 
    "Okulondoola n'okupima kukungaanya era ne kusengejja engeri Pulogulaamu gy'etambulamu n'engeri guluupu z'abantu ezisinga gye ziganyulwamu.", 
    " Okulondoola n'okupima kukungaanya era ne kusengejja engeri Pulogulaamu gy'etambulamu n'engeri guluupu z'abantu zonna gye ziganyulwamu."],
    p28:["I1. Abasomesa basalawo obudde, ekifo, n'okutegeka enkiiko okulaba nga buli muntu azetabamu.", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Abasomesa basalawo obudde, ekifo, n'okutegeka enkiiko okusinziira ku bo ng abwe baba baagala oba nga bammemba abamu abatono mu kitundu bwe baba baagala.", 
    "Abasomesa batuukiriza waakiri ekimu ku bino: Okutegeka enkiiko mu budde, ekifo, n'okuteekateeka ekisobozesa abantu bonna okwetabamu n'okwogera nga tewali abakuba ku mukono.", 
    " Abasomesa batuukiriza waakiri bibiri ku bino wammanga : Okutegeka enkiiko mu budde, ekifo, n'okuteekateeka ekisobozesa abantu bonna okwetabamu n'okwogera nga tewali abakuba ku mukono.", 
    " Abasomesa batuukiriza ebintu bino ebisatu: Okutegeka enkiiko mu budde, ekifo, n'okuteekateeka ekisobozesa abantu bonna okwetabamu n'okwogera nga tewali abakuba ku mukono."],
    p29:["I2. Abasomesa ba Pulojekiti bawa abantu ekitiibwa era bakubiriza abantu okuteeseganya.", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Abasomesa bayigiriza abantu ne bababuulira eky'okukola, tebawuliriza era tebassa mu bantu kitiibwa.", 
    "Abasomesa bawuliriza era abantu babakwata bulungi nga babateekamu ekitiibwa.", "Abasomesa bawuliriza ebirowoozo byabwe , babakwata bulungi, era bakubiriza abantu bonna okwogera.", 
    "Abasomesa bawuliriza, abantu babakwata bulungi era bakubiriza abantu okwogerezeganya."],
    p30:["I3. Nga tumaze okukola enkiiko n'abasomesa, tuwulira muli nga;", 
    " Obutamanya/okumanya eby'olumaggamagga", 
    "Kubadde kumala budde; okujja tutuusa luwalo kuba tetulina kya kkola.", 
    "Tuwulira ebirowoozo ebipya naye tetumanyi kyakubikolera.", 
    "Tuwulira ebirowoozo ebipya era abasomesa batubuulira engeri y'okubikwatamu",
    "Tusoma era ne tuwulira ebirowoozo ebipya era ffenna wamu ne tusalawo eky'okukola."],
    p31:["I4. (Wano wa basomesa bokka) Tuwulira nga tuwagiddwa bulungi (tufuna okutendekebwa buli kiseera, tutegeera bye tukola n'ensonga lwaki tubikola, tulina n'embalirira) ekitongole ekiteeka Pulogulaamu mu nkola/ekitongole kya gavumenti okusobola okukola obulungi omulimu gwaffe", 
    "Obutamanya/okumanya eby'olumaggamagga", 
    "Ekitongole ekiteeka mu nkola Pulogulaamu/ekitongole kya gavumenti tekirina kye kikola okuwagira emirimu gyaffe", 
    "Tufuna obuwagizi n'okuyambibwako mu nsonga bbiri ku zino wammanga a) Tufuna okutendekebwa okw'omujjirano (Omulundi si gumu) mu lulimi lwaffe olunansi, b) Tumanyi bulungi kye tukola na lwaki kya mugaso, c) tusobola okukyusa omuwendo gw'enkiiko mwe tusomeseza n'obudde bwazo okusobola okugya mu budde bw'abantu, d) Tufuna ebifo we tutegekera emisomo, kwossa ebikozesebwa byonna ebituyamba okuddukanya enkiiko/emisomo gino okuva mu kitongole ekiteeka mu nkola pulogulaamu, e) Emirimu gyaffe gisoboka (tetusuubirwa kukola mu byalo bingi oba okutambula engendo empanvu oba okukola enkiiko eziwera)", 
    "Tufuna obuyambi mu nsonga ssattu ku zino wammanga a) a) Tufuna okutendekebwa okw'omujjirano (Omulundi si gumu) mu lulimi lwaffe olunansi, b) Tumanyi bulungi kye tukola na lwaki kya mugaso, c) tusobola okukyusa omuwendo gw'enkiiko mwe tusomeseza n'obudde bwazo okusobola okugya mu budde bw'abantu, d) Tufuna ebifo we tutegekera emisomo, kwossa ebikozesebwa byonna ebituyamba okuddukanya enkiiko/emisomo gino okuva mu kitongole ekiteeka mu nkola pulogulaamu, e) Emirimu gyaffe gisoboka (tetusuubirwa kukola mu byalo bingi oba okutambula engendo empanvu oba okukola enkiiko eziwera)", 
    "Tufuna okuyambibwako mu nsonga zino zonna wammanga; a) Tufuna okutendekebwa okw'omujjirano (Omulundi si gumu) mu lulimi lwaffe olunansi, b) Tumanyi bulungi kye tukola na lwaki kya mugaso, c) tusobola okukyusa omuwendo gw'enkiiko mwe tusomeseza n'obudde bwazo okusobola okugya mu budde bw'abantu, d) Tufuna ebifo we tutegekera emisomo, kwossa ebikozesebwa byonna ebituyamba okuddukanya enkiiko/emisomo gino okuva mu kitongole ekiteeka mu nkola pulogulaamu, e) Emirimu gyaffe gisoboka (tetusuubirwa kukola mu byalo bingi oba okutambula engendo empanvu oba okukola enkiiko eziwera)",]
    }
