const basics={
    figure1:"Kielelezo ",
    figure2:" ya 5. Bofya vishale kwa matokeo zaidi.",
    h1:"Taarifa za Msingi za Mpango",
    program:"Jina la Mpango",
    organization:"Jina la Shirika",
    orgtype:"Aina ya shirika",
    country:"Nchi za Upangaji",
    region:"Mikoa/Maeneo (ikiwezekana)",
    name:"Majina yanayokamilisha tathmini hii",
    date:"Tarehe Iliyokamilika",
    stage:"Hatua",
    save:"Hifadhi data",
    sendmail:"Barua pepe kwa data",
    comment:"Maoni"
}
const stages=['pilot','new','midterm','mature','complete'];
const orgtypes=["Mwisho wa Serikali ya Mitaa/serikali","yasiyo ya faida/ asasi ya kiraia"];

const clickto="Bofya ili kuhifadhi maoni";
const comment="Maoni";

const dimensions=[
    "A: Ushiriki, Ujumuishi, na Sauti",
    "B: Rasilimali za Mitaa na Maarifa",
    "C: Uendelevu",
    "D: Mbinu za Uwajibikaji.",
    "E: Uitikiaji kwa Mienendo Maalum ya Muktadha",
    "F: Ushirikiano ndani na miongoni mwa jamii",
    "G: Kufanya Kazi na Asasi za Kiraia/Serikali za Mitaa",
    "H. Mbinu za Ufuatiliaji na Tathmini zinasaidia CLD",
    "I. Uwezeshaji Uwekezaji na Nguvu"];
    

const rubric={
    p2:["A1. Mpango wa CLD unahakikisha ushiriki wa vikundi vilivyotengwa.",
    "Hakuna/habari isiyotosha kufanya uamuzi.",
    "Mambo yanayowezekana ya kutengwa (jinsia, kabila, umri, hali ya kiuchumi) ni haijachanganuliwa.",
    "Watekelezaji wamebainisha mambo yanayoweza kusababisha kutengwa na ni pamoja na maoni ya wanajamii hawa. ",
    "Watekelezaji huimarisha sauti ya pamoja katika jamii ya wale wanaoweza kutengwa na kujenga mshikamano wa jamii. Kumbuka: kuwa na sauti na kusikilizwa lakini sio wafanya maamuzi",
    "Wale ambao wana hatari ya kutengwa ni wahusika wakuu katika kufanya maamuzi katika mpango. Kumbuka: kuwa na sauti, kusikilizwa na ni watoa maamuzi"],
    p3:["A2. Wanajamii huamua lengo la CLD mpango KABLA ya muundo halisi wa programu.",
    "Hapana/maelezo yasiyotosha kufanya uamuzi.",
    "Wanajamii hawakuhusika katika mchakato wa tathmini.",
    "Wanajamii walishiriki kikamilifu katika mchakato wa tathmini na walihusika katikaya yafuatayo : (1) kubuni mchakato (2) kukusanya data; (3) kuchambua data; (4) kuandaa mahitimisho.",
    "Wanajamii walishiriki kikamilifu katika mchakato huo na walihusika katika mawili au matatu kati ya yafuatayo: (1) kubuni mchakato (2) kukusanya data; (3) kuchambua data; (4) kuandaa mahitimisho.",
    "Wanajamii walihusika katika yote yafuatayo: (1) kubuni mchakato (2) kukusanya data; (3) kuchambua data; (4) kuunda hitimisho."],
    p4:["A3. Wanajamii wana jukumu kubwa katika muundo wa programu ya CLD",
    "Hapana/habari haitoshi kufanya uamuzi.",
    "Wanajamii hawakuhusika katika mchakato wa kubuni.",
    "Msingi wa muundo wa programu unatokana na wanajamii waliochaguliwa (kmviongozi au wawakilishi lakini hakuna ushiriki wa wanajamii wengi zaidi)",
    "Msingi wa muundo wa programu unatokana na michakato mingi ya ushirikishwaji wa jamii lakini bila kuzingatia nguvu/mienendo ya kijinsia, mgawanyo wa rasilimali ndani ya jamii, viwango tofauti vya umaskini, n.k." ,
    "Msingi wa muundo wa programu unatokana na michakato mingi ya ushirikishwaji wa jamii kwa kuzingatia nguvu/mienendo ya kijinsia, mgawanyo wa rasilimali ndani ya jamii, viwango tofauti vya umaskini, n.k. Mawazo haya yanatumika kuunda dira na mipango ya utekelezaji."],
    p5:[
    "A4. Wanajamii wana jukumu kubwa katika utekelezaji wa mpango wa CLD (pamoja na urekebishaji)",
    "Hakuna/habari isiyotosha kufanya uamuzi.",
    "Wanajamii hawakuhusika katika mchakato wa utekelezaji.",
    "Chagua wanajamii (km viongozi au viongozi au watu wengine)wawakilishi) wanafahamishwa kuhusu utendaji wa programu na maamuzi kuhusu utekelezaji au urekebishaji.",
    "Wanajamii na viongozi wa eneo wanafahamishwa kuhusu utendaji wa programu na wanaweza kuathiri ufanyaji maamuzi kuhusu shughuli za programu, na urekebishaji.",
    "Wanajamii (pamoja na wale walio katikahatari ya kutengwa) na viongozi wa eneo huendesha ufanyaji maamuzi kuhusu shughuli zinazoendelea za programu, mapitio ya utendaji wa programu na mahitaji yoyote ya kurekebishwa."],
    p6:[
    "A5. Kasi ya mpango wa CLD imedhamiriwa kwa ushirikiano na jamii na, inapofaa, na wafadhili",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Kasi ya mpango huamuliwa na shirika/wafadhili wanaotekeleza bila mashauriano ya jumuiya. na usambazaji wa habari.",
    "Kasi ya programu huamuliwa na shirika/mfadhili anayetekeleza. Jamii inaarifiwa kuhusu kasi na maoni ya jumuiya yanapopatikana (lakini hayafanyiwi kazi)",
    "Kasi ya programu huamuliwa na shirika/mfadhili tekelezaji kwa ushirikiano/kwa kushauriana na wanajamii.",
    "Kasi ya Mpango wa mpango huamuliwa kwa ushirikiano na wanajamii wakiwemo wawakilishi wa makundi yaliyotengwa. Inatambua kasi tofauti inayopendelewa na vikundi tofauti katika jamii."],
    p7:[
    "A6. Mpango wa CLD kwa utaratibu hujenga sauti na imani ya wanajamii, hasa wale walio katika hatari ya kutengwa, kueleza mawazo yao, mawazo, kubadilishana uzoefu, n.k.",
    "Hapana/habari haitoshi kufanya uamuzi.",
    "Programu hufanyahakuna juhudi za kujenga sauti na kujiamini ",
    " Mpango huu unaweza kujenga sauti na kujiamini miongoni mwa baadhi ya wanajamii na/au viongozi wa eneo lakini hauna mbinu ya utaratibu wa kuifanya.",
    " Mpango huu una nia ya kujenga sauti na imani miongoni mwa wanajamii. na/au viongozi wa mitaa kwa kuwajengea uwezo na ushauri.",
    "Programu ina nia ya kujenga sauti na imani ya viongozi wa mitaa na wanajamii, ikiwa ni pamoja na wale walio katika hatari ya kutengwa (kuwawezesha kujifunza, kufanya mazoezi ya jinsi ya kueleza na kuwasilisha. mawazo miongoni mwa mambo mengine)"],
    p8:[
    "A7. Mpango wa CLD huongeza ufahamu na kujenga ujuzi wa utetezi miongoni mwa miundo ya mitaa, viongozi, na wanajamii ili kushinikiza haki zao za kijamii, kiuchumi na kisiasa",
    "Hakuna/habari isiyotosha kufanya uamuzi.",
    "Programu haileti ufahamu wa haki za watu kijamii, kiuchumi na kisiasa wala haijengi stadi za utetezi",
    "Programu hii inakuza uelewa wa watu kuhusu haki za kijamii, kiuchumi na kisiasa lakini haijengi stadi za utetezi",
    "Programu hii inakuza uelewa wa watu kijamii, kiuchumi na kijamii. haki za kisiasa na kujenga ujuzi wa utetezi",
    "Programu hii inakuza ufahamu wa haki za watu kijamii, kiuchumi na kisiasa na kujenga utetezi na stadi za harakati za kijamii"],
    p9:[
    "B1. Mpango wa CLD unajengwa juu ya Rasilimali na Maarifa za Mitaa",
    "Hakuna/habari isiyotosha kufanya uamuzi.",
    "Programu haizingatii rasilimali na maarifa ya ndani.",
    "Programu inafahamu rasilimali za ndani, lakini ujuzi hupitishwa na wafanyakazi wa mstari wa mbele.",
    "Programu inajengwa juu ya rasilimali za ndani na inazingatia ujuzi wa ndani.",
    "Mpango unatumia na kusherehekea ujuzi na rasilimali za ndani. *sherehe inarejelea kutambua thamani ya maarifa ya wenyeji na kuyafuatilia."],
    p10:[
    "Jumuiya ya B2 inachangia rasilimali zao (km wakati, pesa taslimu, kazi, ardhi, nyenzo, n.k.)",
    ​​"Hakuna/habari isiyotosha kutengeneza uamuzi.",
    "Jumuiya haichangii utekelezaji wa programu kwa pesa taslimu au fadhili au kazi.",
    "Wanajamii huchangia wakati/kazi au rasilimali (ardhi, pesa taslimu, nyenzo), lakini kwa sababu tu ni lazima.",
    "Jumuiya wanachama huchangia muda/kazi au rasilimali (ardhi, fedha taslimu, nyenzo), wanapoulizwa lakini hawajitolea.",
    "Wanajamii huamua kinachohitajika, kwa hiari kutambua rasilimali za ziada ambazo zingechangia matokeo (muda/kazi, ardhi, fedha taslimu. , nyenzo) na ujitolee."],
    p11:[
    "C1. Jumuiya ni muhimu katika kuandaa mikakati ya kuondoka kwa mpango wa CLD",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Hakuna mkakati wa kuondoka.",
    "Mkakati wa kuondoka unaundwa na shirika linalotekeleza bila kushauriana na viongozi wa jumuiya au wanajamii.",
    "Mkakati wa kuondoka umeundwa kwa kushauriana na viongozi wa eneo na wanajamii.",
    "Mkakati wa kuondoka unamilikiwa na wanajamii na viongozi wa eneo."],
    g11:[
    "Jumuiya za C1 ni muhimu katika kuunda mikakati ya mwendelezo kwa mpango wa CLD",
    "Hakuna/habari haitoshi kutoa uamuzi.",
    "Hakuna mkakati wa kuendelea.",
    "Mkakati wa mwendelezo unaundwa na viongozi wa serikali za mitaa bila kushauriana na viongozi wa jumuiya, jumuiya za kiraia au wanajamii",
    "Mkakati wa mwendelezo umeundwa kwa kushauriana na viongozi wa eneo, jumuiya ya kiraia au wanajamii.",
    "Mkakati wa mwendelezo unamilikiwa na wanajamii na viongozi wa eneo."],
    p12:[
    "C2. Kupanga kwa ajili ya kuondoka kuwajibika kunasukwa katika mpango mzima wa CLD [awamu zote za mzunguko wa maisha]",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Hakuna mikakati ya kuondoka.",
    "Mikakati ya kuondoka imeundwa kuelekea mwisho. ya programu (karibu sana na kufungwa au kufungwa)",
    "Mikakati ya kuondoka hupangwa wakati wa kubuni na kuangaliwa upya hadi mwisho wa programu (karibu sana na kufungwa au kufungwa)",
    "Mipango ya mikakati ya kuondoka ilianza ilianza. katika usanifu, hurekebishwa mara kwa mara wakati wa utekelezaji na kukamilishwa hadi mwisho wa programu."],
    g12:[
    "Upangaji wa C2 kwa ajili ya mwendelezo unasukwa katika mpango mzima wa CLD",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Hapo hakuna mikakati ya mwendelezo.",
    "Mikakati ya mwendelezo imeundwa kuelekea mwisho wa programu au kuelekea mwisho wa muhula wa serikali.",
    "Mikakati ya mwendelezo hupangwa wakati wa kubuni na kuangaliwa upya hadi mwisho wa programu au karibu na mwisho wa muhula (karibu sana na kufungwa au kufungwa ure)",
    "Upangaji mwendelezo unaoanzishwa wakati wa usanifu, hurekebishwa mara kwa mara wakati wa utekelezaji na kukamilishwa hadi mwisho wa mpango au karibu na mwisho wa muhula."],
    p13:[
    "C3. Mikakati ya kuondoka kwa mpango wa CLD inaelezea taratibu zilizoachwa ili kuhakikisha uendelevu na/au uthabiti",
    "Hakuna/habari isiyotosha kufanya uamuzi.",
    "Hakuna mikakati ya kuondoka.",
    "Kuna mkakati wa kuondoka lakini hufanya hivyohaielekei kwenye uendelevu au taratibu za ustahimilivu.",
    "Kuna mpango wa kimantiki ambao unaelezea taratibu ambazo athari inayotarajiwa itaendelea baada ya uingiliaji kati kumalizika.",
    "Kuna mpango wa kimantiki unaoelezea taratibu ambazo athari huamuliwa na jumuiya. wanachama wataendelea baada ya afua kukamilika. Hii ni pamoja na tathmini ya uwezo/rasilimali zinazohitajika na watendaji ndaniwa.",
    "Hakuna mikakati ya mwendelezo.",
    "Kuna mkakati wa mwendelezo lakini hauelekezi kwenye mifumo endelevu na ustahimilivu.",
    "Kuna mpango wa kimantiki ambao unaelezea njia ambazo athari inayotarajiwa itaendelea baada ya programu kumalizika au serikali imebadilika.",
    "Kuna mpango wa kimantiki unaoelezea taratibu ambazo athari zitakazoamuliwa na wanajamii zitaendelea baada ya uingiliaji kati kumalizika. Hii inajumuisha tathmini ya uwezo/rasilimali zinazohitajika na watendaji wa ndani."],
    p14:[
    "C4. Athari za mpango wa CLD hupimwa baada ya kufungwa kwa ushiriki wa ndani",
    "Haitumiki",
    "Athari ya programu haijapangwa au kupimwa kwa miaka 2+ baada ya kufungwa.",
    "Athari ya programu hupimwa (au imepangwa kupimwa) miaka 2+ kufungwa baada ya programu. Watendaji wa jumuiya wanafahamishwa kuhusu zoezi hilo na kutoa taarifa kama ilivyoombwa.",
    "Athari za programu hupimwa miaka 2+ baada ya kufungwa kwa programu. Wahusika wa jumuiya wanashauriwa kuhusu zoezi hilo na kutoa taarifa kama ilivyoombwa.",
    "Athari za programu hupimwa miaka 2+ baada ya kufungwa kwa programu. Watendaji wa jumuiya ni washiriki hai katika hatua zote za tathmini ya baada ya programu (kubuni kuripoti kwa mpango kazi)."],
    g14:[
    "Kipimo cha C4 cha athari za mpango wa CLD kinawekwa kitaasisi na kinaendelea baada ya mabadiliko katika serikali." ,
    "Haitumiki",
    "Athari za programu hazijapangwa au kupimwa baada ya kufungwa/ mabadiliko ya serikali.",
    "Athari ya programu hupimwa (au imepangwa kupimwa) miaka 2+ baada ya kufungwa kwa programu/mabadiliko ya serikali. Watendaji wa jumuiya wanafahamishwa kuhusu zoezi hilo na kutoa taarifa kama ilivyoombwa.",
    "Athari za programu hupimwa miaka 2+ baada ya kufungwa kwa programu/mabadiliko ya serikali. Wahusika wa jumuiya wanashauriwa kuhusu zoezi hili na kutoa taarifa kama ilivyoombwa.",
    "Athari za programu hupimwa miaka 2+ baada ya kufungwa kwa programu/mabadiliko ya serikali. Watendaji wa jumuiya ni washiriki hai katika hatua zote za tathmini (kubuni kuripoti kwa mpango kazi)"],
    p15:[
    "C5. Wanajamii (pamoja na waliotengwa zaidi) bado wananufaika na mpango wa CLD",
    "Haitumiki",
    "Mpango haujaacha athari inayoweza kufuatiliwa (chanya, hasi, isiyo na upande)",
    "Ushahidi mdogo wa athari endelevu unaonekana. Hapana hadi kubadilika kidogo kumetokea.",
    "Athari mchanganyiko lakini mara nyingi chanya. Wanajamii na/au miundo imejizoeza urekebishaji na ujuzi uliopatikana kutoka kwa mpango wa CLD.",
    "Ushahidi mzuri zaidi. Wanajamii na/au miundo mara kwa mara imetumia mbinu na ujuzi wa kujirekebisha uliopatikana kutoka kwa mpango wa CLD."],
    g15:[
    "Wanajumuiya wa C5 (pamoja na waliotengwa zaidi) wanaendelea kunufaika na mpango wa CLD baada ya mabadiliko katika serikali",
    "Haitumiki ",
    " Mpango haujaacha athari inayoweza kufuatiliwa (chanya, hasi, isiyo na upande)",
    "Ushahidi mdogo wa athari endelevu unaonekana. Hakuna au kubadilika kidogo kumetokea.",
    "Athari mchanganyiko lakini mara nyingi chanya. Wanajamii na/au miundo imejizoeza urekebishaji na ujuzi uliopatikana kutoka kwa mpango wa CLD.",
    "Ushahidi mzuri zaidi. Wanajamii na/au miundo mara kwa mara imetumia mbinu na ujuzi wa kujirekebisha uliopatikana kutoka kwa mpango wa CLD."],    
    p16:[
    "D1 Mpango huu unakuza ushirikiano na uwajibikaji wa kweli wa pande zote",
    "Hakuna/habari isiyotosha kufanya uamuzi.",
    " Hakuna taratibu za uwajibikaji zinazohusisha jamii.",
    "Taratibu za uwajibikaji zipo ama kutoka kwa jamii hadi mashirika ya utekelezaji, au kutoka kwa wakala wa utekelezaji hadi kwa jamii.",
    "Njia mbili za uwajibikaji zipo kati ya jamii na wakala wa utekelezaji.",
    "Taratibu za uwajibikaji. hayafanyiki tu kati ya jumuiya na mashirika ya utekelezaji, bali ndani ya jumuiya zenyewe na/au na viongozi wa mitaa (vikundi au mabaraza yaliyochaguliwa)."],
    p17:[
    "D2. Mpango wa CLD hutoa utaratibu wa kutoa maoni kwa jamii katika kipindi chote cha maisha ya mradi, ikijumuisha kupitia mazoezi ya M&E",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Hakuna mbinu za maoni.",
    "Maoni kwa jumuiya inaachiwa wawezeshaji bila mbinu za kimfumo.",
    "Maoni kwa jamii hutolewa tu wakati masuala muhimu yanapotokea.",
    "Kulingana na data ya M&E, mazoezi ya ugatuzi ya ujifunzaji shirikishi hutumiwa kutoa mrejesho kwa jamii kwa njia ya utaratibu na kuwasaidia. fanya mipango ya kushughulikia masuala muhimu."],
    p18:[
    "E1. Mpango wa CLD ni mwitikio kwa tofauti nyingi za nguvu na mienendo (kwa mfano jinsia, hali ya kiuchumi, kabila, n.k.)",
    ​​"Hapana/habari haitoshi kufanya uamuzi.",
    "Programu haitathmini au kuzingatia tofauti za nguvu na mienendo. katika jamii.",
    "Tathmini za muundo wa programu zinaonyesha tofauti na mienendo, lakini hakuna mkakati wa kuzingatia tofauti hizi.",
    "Uchambuzi wa jamii unaonyesha tofauti ya muktadha katika uhusiano wa nguvu, lakini sio programu wala wawezeshaji vifaa vya kuyashughulikia.",
    "Programu ni msikivu kwa tofauti za mamlaka na mienendo ndani na katika jumuiya na wawezeshaji wameandaliwa kuzishughulikia/kuziendesha."],
    p19:[
    "E2. Mpango wa CLD ni msikivu kwa mahitaji na miktadha ya jumuiya",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Programu haiwezi kujibu mahitaji ya kimuktadha ya jumuiya (mpango unatumia mkabala wa kuchapishwa)",
    "Programu haiwezi kujibu kubadilisha mahitaji na muktadha wa jumuiya, lakini shirika tekelezi linatafuta afua zingine kushughulikia haya.",
    "Programu inaweza kubadilika kwa kiwango fulani, lakini hii ni mdogo kwa sifa za muundo.",
    "Programu ni ya kurudia na inaweza kukabiliana na migogoro, mafanikio au mabadiliko katika mahitaji na mazingira ya jamii. (km mafuriko, ukame, njaa ya msimu, kuwasili kwa teknolojia mpya, mabadiliko ya mifumo ya kisiasa, n.k.)"],
    p20:[
    "F1. Mpango wa CLD hujenga uhusiano wa ushirikiano kwa usawa, wima, na katika jumuiya zote [hupimwa kama kiashirio au kuelezewa kama mchakato]",
    "Hakuna/maelezo yasiyotosha kufanya uamuzi.",
    "Mpango haukusudii kujenga uhusiano wa ushirikiano." ,
    "Mpango huu hujenga mahusiano ya ushirikiano mlalo (km maskini kwa maskini; mwanamke kwa mwanamke; n.k.) ndani ya jamii.",
    "Mpango huu unajenga mahusiano ya ushirikiano ya mlalo na wima (tajiri kwa maskini, tabaka kwa tabaka, mwanamke kwa mwanamume) ndani ya jumuiya.",
    "Programu hujenga mahusiano ya ushirikiano 1. kwa usawa (kijamii na kiuchumi, jinsia, dini); 2. wima (kijamii na kiuchumi, tabaka); 3. katika jumuiya zote."],
    p21:[
    "F2 Mpango wa CLD unaunganisha miundo ya mitaa au viongozi na mashirikisho ya mitaa au mienendo mipana ya kijamii",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Mpango hauunganishi jumuiya ya wenyeji. miundo au viongozi kwa mashirikisho au vuguvugu lolote.",
    "Mpango huu unaunganisha miundo ya jumuiya za mitaa au viongozi na mashirikisho ya mitaa.",
    "Mpango huu unaunganisha miundo ya jumuiya za mitaa au viongozi kwa shirikisho za mitaa na za kikanda.",
    "Mpango huu unaunganisha miundo ya jumuiya za mitaaau viongozi wa mashirikisho ya serikali za mitaa na kikanda na harakati za kijamii kitaifaza.",
    "Serikali ya Wilaya au Wilaya haifahamu mpango huo.",
    "Serikali ya Wilaya au Wilaya inafahamu kuhusu mpango huo, lakini hakuna jukwaa/ nafasi ya mwingiliano kati ya miundo shirikishi ya jumuiya au viongozi na maofisa wa wilaya ndogo au wilaya.",
    "Serikali ya Wilaya au Wilaya inafahamu kuhusu mpango huo, na kuna mwingiliano wa dharura kati ya miundo shirikishi ya jumuiya au viongozi na watendaji wa wilaya au wilaya. Mpango huu unaimarisha uwezo wa jamii kudai haki/stahiki zake kutoka kwa serikali ya kitongoji au wilaya.",
    "Serikali ya Wilaya au Wilaya inafahamu kuhusu mpango wa CLD. Mpango wa CLD huanzisha ushirikiano wa kimfumo kati ya jamii na kitongoji au serikali ya wilaya ili kufikia malengo ya jumuiya."],
    g22:[
        "G1 Mpango wa CLD umeunganishwa na mashirika ya kiraia.",
        "Hapana/habari haitoshi kufanya uamuzi. ",
        "Asasi za kiraia za mitaa (AZAKI) hazifahamu mpango huo.",
        "Mashirika ya kiraia ya mitaa yanafahamu kuhusu mpango huo, lakini hakuna jukwaa / nafasi ya mwingiliano kati ya miundo shirikishi ya jamii au viongozi, AZAKi na ndogo. -watendaji wa wilaya au wilaya.",
        "AZAKi za mitaa zinafahamu mpango huo, na kuna mwingiliano wa dharula kati ya miundo shirikishi ya jamii, AZAKi na maafisa wa vitongoji au wilaya.",
        "AZAKi za mitaa zinafahamu mpango wa CLD. Mpango wa CLD huanzisha ushirikiano wa kimfumo kati ya AZAKi za mitaa, miundo ya jamii na serikali ya kitongoji au wilaya ili kufikia malengo ya jumuiya."],
    p23:[
    "Ufuatiliaji Shirikishi wa H1 unafanywa",
    "Hakuna/habari haitoshi kufanya uamuzi. ",
    "Hakuna ufuatiliaji shirikishi wa jumuiya.",
    "Ufuatiliaji wa jumuiya hutokea lakini unawezeshwa zaidi na wafanyakazi wa mstari wa mbele.",
    "Ufuatiliaji wa jumuiya hutokea na unawezeshwa zaidi na wanajamii. Maoni kwa jumuiya pana [kupitia vikao shirikishi] hata hivyo ni ya dharura.",
    "Ufuatiliaji Ushiriki wa Jumuiya (CPM) ni msingi wa mbinu ya M&E ya programu. Ufuatiliaji wa jumuiya unawezeshwa na wanajamii au miundo na inajumuisha kutoa taarifa kwa jumuiya kubwa mara kwa mara kwa mfano kila baada ya miezi sita."],
    p24:[
    "H2 Tathmini shirikishi inafanywa",
    "Hapana/habari haitoshi kufanya uamuzi.",
    "Hakuna tathmini shirikishi ya jumuiya.",
    "Wanajamii wanahusika katika hatua MOJA au MBILI kati ya hizi za tathmini: 1) Kupanga; 2) Ukusanyaji wa Data; 3) Uchambuzi; 4) Uthibitishaji; 5) Hitimisho na Mapendekezo; 6) Mipango ya utekelezaji.",
    "Wanajamii wanahusika katika hatua nyingi (TATU au NNE) za tathmini hizi: 1) Kupanga; 2) Ukusanyaji wa Data; 3) Uchambuzi; 4) Uthibitishaji; 5) Hitimisho na Mapendekezo; 6) Mipango ya utekelezaji.",
    "Wanajamii ni muhimu katika hatua ZOTE za tathmini: 1) Kupanga; 2) Ukusanyaji wa Data; 3) Uchambuzi; 4) Uthibitishaji; 5) Hitimisho na Mapendekezo; 6) Upangaji wa utekelezaji."],
    p25:[
    "matokeo ya M&E ya H3 yamegawanywa kulingana na jinsia, ulemavu na tofauti zingine muhimu za kijamii NA kufanyiwa kazi",
    "Hakuna/habari haitoshi kufanya uamuzi.",
    "Hakuna mgawanyiko wa matokeo na tofauti za kijamii.",
    "Matokeo yamegawanywa, lakini idadi ya tofauti za kijamii zinazohusiana na uingiliaji kati hazipo. Kuna maelezo machache ya kufafanua kwa nini matokeo ni tofauti kwa vikundi tofauti.",
    "Matokeo yanagawanywa kulingana na tofauti zote za kijamii zinazohusiana na afua. Kuna baadhi ya maelezo kwa nini matokeo ni tofauti kwa vikundi tofauti na hiyo inamaanisha nini kwa mpango.",
    "Matokeo yanagawanywa kulingana na tofauti zote za kijamii zinazohusiana na afua. Kuna maelezo mazuri kwa nini matokeo ni tofauti kwa vikundi tofauti na hiyo inamaanisha nini kwa programu [iliyotafsiriwa kwa hatua iliyopendekezwa]."],
    p26:[
    "I1 Wawezeshaji wa programu ya CLD (iwe ni viongozi wa jumuiya, wafanyakazi au washirika kuwezesha. ) wamepewa ujuzi na mazoezi kwa ajili ya majukumu yao.",
    "Hakuna/taarifa haitoshi kufanya uamuzi.",
    "Wawezeshaji wanapata mwelekeo wa kimsingi katika mazingira/mipangilio rasmi ya mafunzo kwa mfano darasani.",
    "Wawezeshaji wanafunzwa ujuzi wa kimsingi wa uwezeshajipamoja na uchambuzi na upangaji shirikishi katika mazingira rasmi ya mafunzo (mfano darasani)",
    "Wawezeshaji wanafunzwa katika stadi za uwezeshaji, uchambuzi shirikishi na upangaji darasani na katika jamii.",
    "Wawezeshaji wanafunzwa stadi za uwezeshaji, uchambuzi shirikishi na kupanga, pamoja na hatua za pamoja darasani na katika jamii."],
p27:[
"I2 The CLD program has reasonable provisions to ensure flexibility to respond to changes in demand for community facilitators (e.g. with scale of program, changes in context or pace of CLD)",
"No/insufficient information to make a judgement.",
"No assessment of changes in demand for community facilitators AND/OR No resource provision for increasing scale of program AND/OR No processes in place for reducing numbers of facilitators or slowing pace of program.",
"Ad-hoc assessments of numbers and capacity of community facilitators relative to the context, intended scale of the program and pace of the program. Changes are made if program performance has suffered.",
"Regular assessments of numbers and capacity of community facilitators relative to the context, intended scale of the program and pace of the program. Changes are made ONLY if program performance has suffered.",
"Regular assessments of numbers and capacity of community facilitators relative to the context, intended scale of the program and pace of the program. Program has budgetary provisions and processes in place to respond."],
p28:[
"I3 The CLD program has reasonable provisions to support the quality of local facilitation (clear intake criteria; knowledge and skills assessment; provision of training and support for local facilitators)",
"No/insufficient information to make a judgement.",
"There is no provision to support quality of local facilitation. There is no clear intake criteria, no proper knowledge and skills assessment is undertaken and there is no provision for training and support of local facilitators.",
"There is some ad-hoc provision to support local facilitation. The program has one of the following components built into it: 1) There is a clear intake criteria; 2)  proper knowledge and skills assessment is undertaken; 3) there is provision for training and support of local facilitators.",
"There is a reasonably good provision to support local facilitation. The program has two of the following components built into it: 1) There is a clear intake criteria; 2)  proper knowledge and skills assessment is undertaken; 3) there is provision for training and support of local facilitators.",
"Provisions to support local facilitation are fully integrated into the program. The program has all of the following components built into it: 1) There is a clear intake criteria; 2)  proper knowledge and skills assessment is undertaken; 3) there is provision for training and support of local facilitators."]
}
