const basics={
     figure1:"Nɔnɔmetata ",
     figure2:" of 5. Zi aŋutsrɔeawo dzi be nàkpɔ emetsonu bubuwo.",
     h1:"Dɔwɔɖoɖoa Ŋuti Nyatakaka Veviwo",
     program:"Ðoɖowɔɖi ƒe Ŋkɔ",
     organization:"Habɔbɔ ƒe Ŋkɔ",
     orgtype:"Habɔbɔ ƒe ƒomevi:",
     country:"Dukɔ(wo) si le ɖoɖo wɔm",
     region:"Nutowo/Nuto (ne ehiã)",
     name:"Ŋkɔ(wo) si wu dodokpɔ sia nu",
     date:"Ŋkeke si wowu enu",
     stage:"Afɔɖeɖe",
     save:"Dzra nyatakakawo ɖo",
     sendmail:"Email nyatakakaawo",
     comment:"Nyaŋuɖoɖo"
}
const stages=['yameʋukula', 'yeye', 'midterm', 'tsitsi', 'wu enu'];
const orgtypes=["Nutoa me Dziɖuɖu/dziɖuɖu si do ƒome kplii","habɔbɔ si mekpɔa viɖe aɖeke tso eme o/ dukɔmeviwo ƒe habɔbɔ"];

const clickto="Zi edzi be nàdzra nyaŋuɖoɖo ɖo";
const comment="Nyaŋuɖoɖo";

const dimensions=[
"A: Gomekpɔkpɔ, Amewo ƒe Ðekawɔwɔ, Kple Gbe",
"B: Nutoa me Dɔwɔnuwo kple Sidzedze",
"C: Nusiwo li tegbee kple tɔtrɔ ƒe aɖaŋuɖoɖo",
"D: Akɔntabubu ƒe Mɔnuwo.",
"E: Ŋuɖoɖo ɖe Nya siwo ƒo xlãe ŋu",
"F: Nuwɔwɔ aduadu",
"G: Dɔwɔwɔ kple nutoa me dziɖuɖu/ dukɔmeviwo ƒe habɔbɔwo",
"H: Kpɔkpɔ kple Dzodzro ƒe Nuwɔnawo",
"I: Kpekpeɖeŋunana"];

const rubric={
p2:["A1. Ðoɖowɔɖia kpɔa egbɔ be amewo ƒe hatsotsowo katã le nutoa me (abe ame tsitsiwo kple ɖekakpuiwo, ŋutsuwo kple nyɔnuwo, amesiwo ƒe ganyawo nyo wu kple ame dahewo, tso to vovovowo, ameƒomevi vovovowo, subɔsubɔhawo, kple bubuawo me ene)",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖoa mebua amewo ƒe hatsotso vovovo siwo le kɔƒe aɖe me ŋu o.",
"Dɔwɔɖoɖoa bua ƒuƒoƒo aɖewo siwo woɖe le eme (menye wo katã o) ŋu eye wòkpɔa egbɔ be wokpɔ gome le kpekpewo/habɔbɔ ƒe dɔwɔnawo me.",
"Dɔwɔɖoɖoa bua amewo ƒe ƒuƒoƒo akpa gãtɔ ŋu eye wòkpɔa egbɔ be wokpɔ gome le kpekpewo/ ƒuƒoƒo ƒe dɔwɔnawo me.",
"Dɔwɔɖoɖoa bua amewo ƒe ƒuƒoƒowo katã ŋu, ekpɔa egbɔ be wokpɔ gome vevie le kpekpewo/ ƒuƒoƒo ƒe dɔwɔnawo me."],
p3:["A2. Nutoa me tɔwo tsoa nya me le nusiwo woatsɔ aɖo nɔƒe gbãtɔ le CLD ɖoɖoa me HAFI woawɔ ɖoɖoa ƒe ɖoɖowɔwɔ ŋutɔŋutɔ.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo mekpɔa gome le ɖoɖoa ƒe nu vevitɔwo ŋuti nyametsotso wɔwɔ me o.",
"Nutoa me tɔ tiatia aɖewo (e.g. dekɔnu kplɔlawo, anyigbatɔwo, kple bubuawo) alo ƒuƒoƒowo kpɔa gome le nyametsotso wɔwɔ le ɖoɖowɔɖia ƒe nu vevitɔwo ŋu me.",
"Nutoa me ƒuƒoƒo akpa gãtɔ kpɔa gome le nyametsotso wɔwɔ le nusiwo woatsɔ aɖo nɔƒe gbãtɔ le ɖoɖoa ŋu me.",
"Nutoa me ƒuƒoƒowo katã kpɔa gome le ɖoɖowɔɖia ƒe nu vevitɔwo ŋuti nyametsotso wɔwɔ me eye gbe sɔ le eme."],
p4:["A3. Nutoa me tɔwo wɔa akpa vevi aɖe le CLD ɖoɖowo ƒe ɖoɖowɔwɔ me le woƒe nutoa me.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo mekpɔa gome le ɖoɖowɔwɔ ƒe ɖoɖoa me o.",
"Nutoa me tɔ tiatia (e.g. dekɔnu kplɔlawo, anyigbatɔwo, kple bubuawo) alo ƒuƒoƒowo kpɔa gome le ɖoɖowɔwɔ ƒe ɖoɖoa me.",
"Nutoa me ƒuƒoƒo akpa gãtɔ kpɔa gome le ɖoɖowɔwɔ ƒe ɖoɖoa me.",
"Nutoa me ƒuƒoƒowo katã kpɔa gome le ɖoɖowɔwɔ ƒe ɖoɖoa me eye gbe sɔ le eme."],
p5:["A4. Nutoa me habɔbɔ siwo le ƒuƒoƒo kple nutoawo katã teƒe la wɔa ɖoɖoa.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"NGO-wo alo nutoa me kplɔla siwo li fifia wɔa ɖoɖoa.",
"NGO-wo kple/alo nutoa me kplɔlawo ɖoa habɔbɔ si awɔ ɖoɖoa alo awɔ dɔ kple habɔbɔ si li xoxo si me hameviwo tso ƒuƒoƒoawo katã me manɔ o.",
"Dɔwɔha siwo me ame siwo woɖo wo ɖokui le siwo le ƒuƒoƒo kple nutoawo katã teƒe le la wɔa ɖoɖoa.",
"Dɔwɔha tiatia siwo le ƒuƒoƒo kple nutoawo katã teƒe la wɔa ɖoɖoa."],
p6:["A5. Ðoɖowɔɖia tua nutoa me teƒenɔlawo ƒe gbe kple kakaɖedzi ɖo be woakpɔ ŋusẽ ɖe/atrɔ asi le nyametsotsowɔwɔ ŋu.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa medzea agbagba aɖeke be yeatu nutoa me teƒenɔlawo ƒe gbe alo kakaɖedzi ɖo o.",
"Dɔwɔɖoɖoa tua gbe kple kakaɖedzi ɖo le nutoa me teƒenɔla aɖewo dome, gake menye amesiwo tso ƒuƒoƒo siwo woɖe ɖa me o.",
"Dɔwɔɖoɖoa tua gbe kple kakaɖedzi ɖo le nutoa me teƒenɔla geɖewo dome siwo dome amesiwo tso ƒuƒoƒo aɖewo siwo woɖe le eme hã le.",
"Dɔwɔɖoɖoa tua gbe kple kakaɖedzi ɖo le nutoa me teƒenɔlawo katã dome siwo dome amesiwo tso ƒuƒoƒo siwo katã woɖe ɖa me hã le."],
p7:["A6. Ðoɖoa doa amewo ƒe susu ɖe gomenɔamesiwo ŋu (hadomegbenɔnɔ, ganyawo kple dunyahehe) eye wòtua aɖaŋuwo ɖo le nutoa me teƒenɔlawo dome be woabia gomenɔamesi mawo.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa medoa nyanyanana ɖe ŋgɔ eye wotua aɖaŋuwo ɖo be woabia gomenɔamesiwo o.",
"Dɔwɔɖoɖoa na amewo nya nu tso gomenɔamesiwo ŋu, gake metu aɖaŋu aɖeke ɖo be woabia wo o.",
"Dɔwɔɖoɖoa na amewo nya nu tso gomenɔamesiwo ŋu, eye wòtua aɖaŋuwo ɖo na ame ʋee aɖewo be woabia wo.",
"Ðoɖoa na amewo nya nu tso gomenɔamesiwo ŋu, eye wòléa fɔ ɖe aɖaŋuwo tutuɖo ŋu le nutoa me teƒenɔla siwo tso ƒuƒoƒowo katã me be woabia wo."],
p8:["B1. CLD ɖoɖoa tua Nutoa me Dɔwɔnuwo kple Sidzedze dzi.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa mebua nutoa me nunɔamesiwo kple sidzedze ŋu o.",
"Dɔwɔɖoɖoa kua nutoa me nunɔamesiwo me, gake gotagome sidzedzewo tsoa dɔwɔla siwo le ŋgɔgbe la gbɔ.",
"Dɔwɔɖoɖoa zãa nutoa me nunɔamesiwo eye wònya nutoa me sidzedze.",
"Dɔwɔɖoɖoa zãa nutoa me sidzedze kple nunɔamesiwo eye wòdea bubu wo ŋu."],
p9:["B2. Nutoa tsɔa woƒe nunɔamesiwo naa (e.g. ɣeyiɣi, cas h, dɔwɔlawo, anyigba, nuwo, kple bubuawo)",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo medzɔa nu ɖe ɖoɖoa dzi wɔwɔ ŋu le ga alo dɔmenyonyo alo dɔwɔɖui me o.",
"Nutoa me tɔwo tsɔa ɣeyiɣi/dɔ alo nunɔamesiwo (anyigba, ga, nuwo) naa elabena enye sedziwɔwɔ.",
"Nutoa me tɔwo tsɔa ɣeyiɣi/dɔ alo nunɔamesiwo (anyigba, ga, nuwo), ne wode dzi ƒo na wo.",
"Nutoa me tɔwo tsoa nya me le nusiwo hiã ŋu, wolɔ̃na faa dea dzesi nunɔamesi bubuwo (ɣeyiɣi/dɔwɔɖui, anyigba, ga, nuwo) eye wotsɔa wo ɖokui nana faa."],
p10:["C1. Nutoa me tɔwo le vevie ŋutɔ le ɖoɖowɔwɔ ɖe alesi woawɔ kple ɣeyiɣi si wòle be woawu ɖoɖoa nu eye woatsɔe ade asi na wo me.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖo aɖeke meli ɖe ɖoɖoa wuwu kple etsɔtsɔ de asi na ame ŋu o.",
"Ðoɖo si wowɔ ɖe ɖoɖoa wuwu kple eƒe asidede asi ŋu la nye esi habɔbɔ si le edzi wɔm lae wɔ eye wonaa nutoa me kplɔlawo alo nutoa me tɔwo nya nu tso eŋu.",
"Wowɔ ɖoɖo si wowɔ ɖe ɖoɖoa wuwu kple eƒe asidede asi ŋu le nuƒoƒo kple nutoa me kplɔlawo kple nutoa me tɔwo me.",
"Nutoa me tɔwo kple nutoa me kplɔlawoe le ɖoɖo si wowɔ ɖe ɖoɖoa wuwu kple edede asi ŋu."],
p11:["C2. Nutoa me tɔwo wɔa dɔ kple habɔbɔ siwo le dɔ wɔm be woato ɖoɖowɔwɔ ɖe ɖoɖowo ƒe asidede kple tɔtrɔ ŋu me ɣesiaɣi ahatrɔ asi le wo ŋu",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖo alo aɖaŋu aɖeke meli na miaƒe habɔbɔa be woatsɔ ɖoɖoawo ade asi na nutoa me tɔwo o",
"Ne ɖoɖoa le nuwuwu gogom (alo ga aɖeke mesusɔ o) ko hafi wowɔa ɖoɖo be woatsɔ ɖoɖoa ade asi na nutoa me tɔwo",
"Wowɔa ɖoɖo be woatsɔ ɖoɖoa ade asi na nutoa me tɔwo le ɖoɖoa ƒe gɔmedzedze eye wogbugbɔ trɔa asi le wo ŋu le ɖoɖoa ƒe nuwuwu alo ne kuxi gã aɖe do mo ɖa",
"Wowɔa ɖoɖo be woatsɔ ɖoɖoa ade asi na nutoa me tɔwo le ɖoɖoa ƒe gɔmedzedze eye wotoa wo me edziedzi kple nutoa me tɔwo be woaɖe nɔnɔme si le nutoa me fifia afia"],
p12:["C3. Ðoɖoa kpɔa egbɔ be ŋutete le nutoa me ƒe ɖoɖowo (abe habɔbɔ siwo le nutoa me, ƒuƒoƒo siwo le ɖoɖowo wɔm) si be woayi edzi awɔ dɔ le asiɖeɖe le wo ŋu vɔ megbe",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa medzea agbagba aɖeke be yeakpɔ egbɔ be nutoa me xɔtuɖoɖowo ƒe ŋutete le wo si be woayi edzi awɔ dɔ le asiɖeɖe le wo ŋu vɔ megbe o.",
"Ðoɖo aɖe li na ɖoɖowɔɖiwo ƒe asitɔtrɔ gake aɖaŋu aɖeke meli si dzi woato akpɔ egbɔ be nutoa me ƒe ɖoɖowo ate ŋu ayi dɔ dzi le asidede asi megbe eye ŋutetewo nanɔ wo si be woaxɔ ga/nunɔamesiwo (abe alesi wòhiã ene)",
"Aɖaŋu aɖe li si dzi woato akpɔ egbɔ be nutoa me ƒe ɖoɖowo ate ŋu ayi edzi awɔ dɔ le asiɖeɖe le wo ŋu megbe gake dɔwɔna aɖeke meli si woatsɔ atu ŋutetewo ɖo be woakpɔ ga/nunɔamesiwo (abe alesi wòhiãe ene) o.",
"Dɔwɔɖoɖoa le dɔwɔnawo wɔm be woatu ŋutete ɖo be woakpɔ egbɔ be nutoa me ƒe ɖoɖowo ate ŋu ayi dɔ dzi le asidede asi vɔ megbe eye woakpɔ ga/nunɔamesiwo (abe alesi wòhiã ene)."],
p13:["C4. Ne wowu enu vɔ la, wodzidzea ɖoɖoa ƒe ŋusẽkpɔɖeamedzi kple nutoa me tɔwo ƒe gomekpɔkpɔ.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖo aɖeke meli be woatsɔ adzidze ɖoɖoa ƒe ŋusẽkpɔɖeamedzi le ewuwu vɔ megbe alo nutoa me tɔwo menya ne ɖoɖo aɖewo li o.",
"Ðoɖowo li be woadzidze ɖoɖoa ƒe ŋusẽkpɔɖeamedzi (alo wodzidzenɛ) le ewuwu vɔ megbe. Wona nutoa me tɔwo nya nu tso dɔa ŋu eye wonaa nyatakakawo abe alesi wobiae ene.",
"Wodzidzea ŋusẽkpɔɖeamedzi (alo woɖoe be woadzidzee) le ɖoɖoa wuwu vɔ megbe eye wobiaa gbe nutoa me tɔwo le dɔa me.",
"Wodzidzea ŋusẽkpɔɖeamedzi (alo woɖoe be woadzidzee) le ɖoɖoa wuwu vɔ megbe eye nutoa me tɔwo nyea gomekpɔla veviedonula le kamededea ƒe akpawo katã me."],
p14:["C5. Ne wotsɔ ɖoɖoa de asi na nutoa me/nutoa me dziɖuɖu ƒe ɖoɖowo vɔ la, nutoa me tɔ siwo le ƒuƒoƒoawo katã me (le kpɔɖeŋu me, nyɔnuwo, sɔhɛwo, ame tsitsiwo, ame dahewo, nuwɔametɔwo, ame ʋɛwo) gakpɔtɔ le viɖe kpɔm tso dɔwɔna siwo nutoa me tɔwo kplɔna me .",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ame aɖeke mekpɔa viɖe aɖeke le ɖoɖowɔɖia ƒe asidede asi megbe o alo ƒuƒoƒo siwo si mɔnukpɔkpɔ le koe yia edzi le viɖe kpɔm.",
"Ðoɖoa yi edzi le vi ɖem na ƒuƒoƒo aɖewo le asiɖeɖe le wo ŋu vɔ megbe gɔ̃ hã.",
"Ðoɖoa yi edzi le vi ɖem na ƒuƒoƒo akpa gãtɔ le asiɖeɖe le wo ŋu vɔ megbe gɔ̃ hã.",
"Ðoɖoa yi edzi le vi ɖem na ƒuƒoƒoawo katã le asiɖeɖe le wo ŋu vɔ megbe gɔ̃ hã."],
p15:["D1. Ðoɖowɔɖia kple nutoa me ƒe ɖoɖowo ma nyatakaka veviwo le kpɔɖeŋu me nusi wɔm wole, nusitae, alesi wozã gae, kple alesi wozã gae.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa megblɔa nyatakaka aɖeke tso nusi wole wɔwɔm, alesi wole wɔwɔm kple nusitae ŋu na nutoa me tɔwo o.",
"Dɔwɔɖoɖoa alo nutoa me habɔbɔwo ma nyatakaka vevi siwo ƒo xlã ɖoɖoa ɣeaɖewoɣi gake nyatakaka akpa gãtɔ meli o.",
"Zi geɖe la, ɖoɖoa alo nutoa me habɔbɔwo ma nyatakakawo ƒo xlã ɖoɖoa (nyatakaka akpa gãtɔ li gake menye wo katãe o)",
"Ðoɖowɔhawo kple nutoa me habɔbɔwo ma nyatakaka siwo ku ɖe ga, ɖoɖowo, kple dɔwɔnawo ŋu kple nutoa me tɔwo edziedzi eye wokpea amewo be woagblɔ woƒe susu."],
p16:["D2. Ðoɖowɔɖia kpɔa nutoa me tɔwo ƒe nyatoƒoetoto/ nyatoƒoetotowo gbɔ.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Mɔ aɖeke meli si dzi nutoa me tɔwo ato atsɔ nyatoƒoetoto alo nyatoƒoetotowo ado goe o.",
"Mɔ aɖe le ɖoɖowɔɖia si na nutoa me tɔwo be woahe woe nyatoƒoetoto/nyatoƒoetoto, gake menye nusi ŋu woate ŋu aɖo alo kakaɖedzi le eŋu o.",
"Mɔnu si ŋu woate ŋu aɖo eye kakaɖedzi le ɖoɖoa ŋu na nutoa me tɔwo be woatsɔ ado nyatoƒoetoto/nyatoƒoetotowo ɖe te, gake womekpɔ nyatoƒoetotoawo gbɔ o.",
"Mɔnu si ŋu woate ŋu aɖo eye kakaɖedzi le ɖoɖoa ŋu na nutoa me tɔwo be woatsɔ akɔ nyatoƒoe/nyatoƒoetotowo, wokpɔ nyatoƒoetotowo gbɔ."],
p17:["D3. Wogblɔa ŋkuléleɖenuŋu kple dodokpɔ me tsonu na nutoa me tɔwo edziedzi.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Womegblɔa nusiwo do tso Kpɔkpɔ kple dodokpɔ me na nutoa me tɔwo gbeɖe o.",
"Ame siwo kpɔ gome le ɖoɖoa me ate ŋu agblɔ nusiwo do tso Kpɔkpɔ kple dodokpɔ me na nutoa me tɔwo ne wose le wo ɖokui me be wodi.",
"Ne kuxiwo do mo ɖa ko hafi woama nusiwo do tso Kpɔkpɔ kple dodokpɔ me na nutoa me tɔwo.",
"Wogblɔa nusiwo do tso Kpɔkpɔ kple dodokpɔ me na nutoa me tɔwo edziedzi."],
p18:["E1. Ðoɖowɔɖia wɔa nu ɖe nutoa me ƒe nuhiahiãwo kple nɔnɔme siwo le tɔtrɔm ŋu.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa mewɔa nu ɖe nutoa me tɔwo ƒe nuhiahiã siwo le tɔtrɔm ŋu o (e.g. tsiɖɔɖɔ, kuɖiɖi, ɣeyiɣi aɖe ƒe dɔwuame, mɔ̃ɖaŋununya yeyewo ƒe vava, tɔtrɔ le dunyahehe ƒe ɖoɖowo me, kple bubuaw",
"Ðoɖowɔɖia te ŋu wɔ tɔtrɔ aɖewo.",
"Dɔwɔɖoɖoa te ŋu trɔna ɖe nutoa me ƒe nuhiahiã siwo le tɔtrɔm ŋu alesi wòhiãe si me esiwo xaxa alo afɔkuwo he vɛ hã le.",
"Dɔwɔɖoɖoa te ŋu trɔna ɖe nutoa me ƒe nuhiahiã siwo le tɔtrɔm ŋu siwo dometɔ aɖewoe nye esiwo xaxa alo afɔkuwo hena vɛ eye wòtua mɔnuwo/ xɔtuɖoɖowo be woatsɔ akpɔ nɔnɔme mawo tɔgbe gbɔ le etsɔme."],
p19:["E2. Woɖoa CLD Dɔwɔɖoɖoa ƒe ablaɖeɖe (si nye, ɣeyiɣi, zi nenie, kple ɣeyiɣi didi si woatsɔ awɔ dɔ kple nutoa me tɔwo) kple nutoa me tɔwo.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo mekpɔa gome le nyametsotso wɔwɔ le alesi ɖoɖowɔɖia azɔe ŋu o.",
"Wona nutoa me tɔwo nya nu tso ɖoɖoa ƒe ablaɖeɖe ŋu.",
"Wobiaa nutoa me tɔ aɖewo le nyametsotso wɔwɔ le alesi ɖoɖoa azɔe ŋu me.",
"Wobiaa nutoa me tɔwo katã, siwo dome ƒuƒoƒo siwo woɖe ɖe aga teƒenɔlawo hã le, le nyametsotso wɔwɔ le alesi ɖoɖoa azɔe ŋu me."],
p20:["F1. Ðoɖowɔɖia tua ƒomedodo nyui ɖo le kesinɔtɔwo kple ame dahewo dome; ame dahewo kple ame dahewo dome.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖoa mebua ganyawo ƒe vovototowo ŋu o.",
"Ðoɖoa tua ƒomedodo ɖo le ame dahewo kple ame dahewo dome.",
"Ðoɖoanyia ƒoa kesinɔtɔwo kple ame dahewo ɖe numedzodzro kple dzeɖoɖo me.",
"Ðoɖoa bia be kesinɔtɔwo kple ame dahewo nawɔ dɔ ɖekae be woaɖo taɖodzinu ɖeka gbɔ."],
p21:["F2. Ðoɖowɔɖia tua ƒomedodo nyuiwo ɖo le ƒuƒoƒo ɖeka ma ke me kple le to vovovowo, ameƒomevi vovovowo, subɔsubɔhawo, kple bubuawo dome.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖoa mebua ameƒomevinyenye/to/subɔsubɔha ƒe vovototowo ŋu o.",
"Dɔwɔɖoɖoa tua ƒomedodo ɖo le ame siwo tso ameƒomevi/to/subɔsubɔha ɖeka me dome be woawɔ dɔ ɖekae hena hadometɔtrɔ.",
"Dɔwɔɖoɖoa naa amewo tso ameƒomevi vovovowo/to/subɔsubɔha vovovowo me le numedzodzro kple dzeɖoɖo me.",
"Dɔwɔɖoɖoa tua ƒomedodo ɖo le ame siwo tso ameƒomevi vovovowo/to/subɔsubɔha vovovowo me dome be woawɔ dɔ ɖekae hena hadometɔtrɔ."],
p22:["F3. Ðoɖowɔɖia tua ƒomedodo nyui ɖo le nyɔnuwo kple nyɔnuwo dome eye, le ŋutsuwo kple nyɔnuwo dome.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Ðoɖoa mewɔa dɔ kple nyɔnuwo o.",
"Ðoɖoa tua ƒomedodo ɖo le nyɔnu siwo tso ƒuƒoƒo ɖeka me dome.",
"Dɔwɔɖoɖoa tua ƒomedodo ɖo le nyɔnuwo ƒe hatsotsowo katã dome ALOO le nyɔnuwo kple ŋutsuwo dome.",
"Ðoɖoa tua ƒomedodo ɖo le nyɔnuwo ƒe hatsotsowo katã dome KPLEE nyɔnuwo kple ŋutsuwo dome."],
p23:["F4. Ðoɖoa doa ka kple nutoa me tɔwo alo woƒe ŋgɔnɔlawo kple kɔƒe bubuwo kple woƒe ŋgɔnɔlawo le nutome, nuto, alo nuto vovovowo me.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa metua nutoa me ƒe kadodowo kple kadodowo ɖo o.",
"Dɔwɔɖoɖoa tua kadodowo ɖo le nutoawo/nutoa me kplɔla siwo tso nutome ɖeka me dome.",
"Dɔwɔɖoɖoa tua kadodowo ɖo le nutoawo/ nutoa me kplɔlawo dome le nutome/ nuto/nutome/dukɔ bliboa me.",
"Dɔwɔɖoɖoa tua kadodowo ɖo le nutoawo dome le dukɔa/nutome/dukɔa ƒe teƒewo katã hena dɔwɔwɔ ɖekae."],
p24:["G1. Ðoɖowɔɖia ƒe nutoa me ƒuƒoƒowo wɔa dɔ ɖekae kple nutoa me dziɖuɖu ƒe ɖoɖowo kple dɔwɔlawo.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔɖoɖoa alo eƒe nutoa me ƒuƒoƒowo kple nutoa me dziɖuɖu ƒe ɖoɖo siwo li fifia kple dɔwɔlawo naa nyatakaka/gbedasi siwo tsi tre ɖe wo nɔewo ŋu.",
"Dɔwɔɖoɖoa alo eƒe nutoa me ƒuƒoƒowo kple nutodziɖuɖu ƒe ɖoɖo siwo li fifia kple dɔwɔlawo mewɔa dɔ ɖekae kura o (ne wole dɔ wɔm ɖe taɖodzinu ɖeka ŋu gɔ̃ hã)",
"Dɔwɔɖoɖoa alo eƒe nutoa me ƒuƒoƒowo kple nutoa me dziɖuɖu ƒe ɖoɖo siwo sɔ fifia kple dɔwɔlawo wɔa dɔ ɖekae ɣeaɖewoɣi le nya aɖewo ŋu.",
"Dɔwɔɖoɖoa kple eƒe nutoa me ƒuƒoƒowo kple nutoa me dziɖuɖu ƒe ɖoɖowo/nuwɔlawo wɔa dɔ ɖekae edziedzi eye wokpena ɖe wo nɔewo ŋu."],
p25:["H1. Nutoa me tɔwo léa ŋku ɖe dɔ veviwo kple ɖoɖoa ƒe ŋgɔyiyi ŋu.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo ƒe gomekpɔkpɔ le ŋkuléleɖenuŋu aɖeke meli o.",
" .Nutoa me ŋkuléle ɖe nu ŋu dzɔna ɣeaɖewoɣi.",
"Nutoa me ŋkuléle ɖe nu ŋu dzɔna edziedzi, gake dɔwɔla siwo le ŋgɔgbe ye kpɔa edzi.",
"Nutoa me ŋkuléle ɖe nu ŋu dzɔna edziedzi eye nutoa me tɔwo alo ɖoɖowoe kpɔa edzi."],
p26:["H2. Wowɔa gomekpɔkpɔ le eme ƒe dodokpɔ.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo ƒe gomekpɔkpɔ le eme ƒe dodokpɔ aɖeke meli o.",
"Nutoa me tɔwo kpɔa gome le dɔwɔna siawo dometɔ ÐEKA alo EVIE me: 1) Ðoɖowɔwɔ; 2) Nyatakakawo Nuƒoƒoƒu; 3) Kukuɖenuŋu; 4) Dzesidede; 5) Nyataƒoƒo kple Aɖaŋuɖoɖowo; 6) Dɔwɔwɔ ƒe ɖoɖowɔwɔ.",
"Nutoa me tɔwo kpɔa gome le dɔwɔna siawo dometɔ geɖe (ETƆ̃ alo ENE) me: 1) Ðoɖowɔwɔ; 2) Nyatakakawo Nuƒoƒoƒu; 3) Kukuɖenuŋu; 4) Dzesidede; 5) Nyataƒoƒo kple Kafukafu; 6) Dɔwɔwɔ ƒe ɖoɖowɔwɔ.",
"Nutoa me tɔwo le vevie le dɔwɔnaawo KAtã me: 1) Ðoɖowɔwɔ; 2) Nyatakakawo Nuƒoƒoƒu; 3) Dzesidede; 4) Dzesidede; 5) Nyataƒoƒo kple Kafukafu; 6) Dɔwɔwɔ ƒe ɖoɖowɔwɔ."],
p27:["H3. Kpɔkpɔ kple dodokpɔdɔwo léa ŋku ɖe alesi ɖoɖoa wɔa dɔ kple amewo ƒe hatsotso vovovowo eye wòɖea vi na woe siwo dometɔ aɖewoe nye nyɔnuwo, nuwɔametɔwo, ame tsitsiwo, ame siwo tso ame ʋɛwo me.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nutoa me tɔwo menya o elabena womekpɔa gome le ŋkuléle ɖe nu ŋu kple wo me dzodzro (M&E) me o ALOO nutoa me tɔwo mekpɔa gome le eme gake M&E ɖoɖowo mebua amewo ƒe hatsotso vovovoawo ŋu esime wole nyatakakawo nu ƒom ƒu alo le wo me dzrom o.",
"Dzidzedzekpɔkpɔ kple dodokpɔ ƒoa nyatakakawo nu ƒu hedzroa wo me be woase alesi ɖoɖoa wɔa dɔ kple ƒuƒoƒo aɖewo le nutoa me eye wòɖea vi na wo gɔme (E.g. ŋutsuwo kple nyɔnuwo, gake menye nuwɔametɔwo o)",
"Ŋkuléle ɖe nu ŋu kple wo me dzodzro ƒoa nyatakakawo nu ƒu hedzroa wo me be woase alesi ɖoɖoa wɔa dɔ kple ƒuƒoƒo akpa gãtɔ le nutoa me eye wòɖea vi na woe gɔme.",
"Ŋkuléle ɖe nyatakakawo ŋu kple wo me dzodzro ƒoa nyatakakawo nu ƒu hedzroa wo me be woase alesi ɖoɖoa wɔa dɔ kple amewo ƒe hatsotso vovovoawo katã eye wòɖea vi na wo kple nusitae gɔme."],
p28:["I1. Dɔdzikpɔlawo tsoa nya me le ɣeyiɣi, teƒe, kple ɖoɖo si woawɔ kpekpeawo ŋu ale be amesiame nate ŋu akpɔ gome le wo me.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Dɔwɔƒea dzikpɔlawo tsoa nya me le ɣeyiɣi, teƒe, kple teƒe si woawɔ kpekpeawo le ŋu le woawo ŋutɔ ƒe nyonyo alo nutoa me tɔ ʋɛ tiatia aɖewo tɔ nu.",
"Dɔwɔlawo doa go nusiwo gbɔna dometɔ ɖeka ya teti: wowɔa ɖoɖo ɖe kpekpewo ŋu le ɣeyiɣi, teƒe, alo nɔnɔme si ana amewo katã nakpɔ gome le eme ahaƒo nu faa.",
"Dɔwɔlawo doa go nusiwo gbɔna dometɔ eve ya teti: wowɔa ɖoɖo ɖe kpekpewo ŋu le ɣeyiɣi, teƒe, kple nɔnɔme si ana amewo katã nakpɔ gome le eme ahaƒo nu faa.",
"Dɔwɔƒea dzikpɔlawo doa go nu etɔ̃ siwo gbɔna la katã: wowɔa ɖoɖo ɖe kpekpewo ŋu le ɣeyiɣi, teƒe, kple nɔnɔme si ana ameawo katã nakpɔ gome le eme ahaƒo nu faa."],
p29:["I2. Dɔa dzikpɔlawo dea bubu ame ŋu eye wodea dzeɖoɖo ƒe dzi ƒo.",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Nudzikpɔlawo ƒoa nuƒo eye wogblɔa nusi woawɔ na amewo, womeɖoa to o, eye womedea bubu ame ŋu o.",
"Nudzikpɔlawo ɖoa to eye wowɔa nu ɖe amewo ŋu bubutɔe.",
"Dɔwɔlawo ɖoa to woƒe susuwo, wowɔa nu ɖe amewo ŋu bubutɔe, eye wodea dzi ƒo na gomekpɔlawo katã be woaƒo nu.",
"Nudzikpɔlawo ɖoa to, wowɔa nu ɖe amewo ŋu bubutɔe, eye wodea dzi ƒo na amewo be woaƒo nu kple wo nɔewo."],
p30:["I3. Ne míede kpekpewo kple nufialawo vɔ la, míesena le mía ɖokui me be:",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Enye ɣeyiɣi gbegblẽ; esi wòle be míade ta koe míedena.",
"Míele susu yeyewo sem gake míeka ɖe nusi míawɔ kpli wo dzi o.",
"Míesea susu yeyewo eye nufialawo gblɔa alesi míawɔ ɖe wo dzii na mí.",
"Míesea susu yeyewo kple nusɔsrɔ̃ yeyewo eye míeƒoa ƒu tsoa nya me le alesi míawɔ nu ɖe wo ŋui ŋu."],
p31:["I4. (Na kpekpeɖeŋunalawo ɖeɖeko) Míesena le mía ɖokui me be habɔbɔ si le dɔ wɔm/dziɖuɖudɔwɔƒe si le dɔ wɔm la doa alɔ mí (míexɔa hehe edziedzi, míesea nusi wɔm míele kple nusitae gɔme, míetrɔna ɖe nɔnɔmewo ŋu kple gazazãwo) be míawɔ míaƒe dɔwo",
"Nye menya o. nyatakaka si mesɔ gbɔ o",
"Habɔbɔ/dziɖuɖudɔwɔƒe si le dɔ wɔm la medzea agbagba aɖeke be yeado alɔ míaƒe dɔa o",
"Míexɔa kpekpeɖeŋu le nuto siawo dometɔ eve me a) míexɔa hehe edziedzi (menye zi ɖeka o) le míaƒe nutoa me gbe me, b) míenya nusi wɔm míele kple nusita wòle vevie, c) míate ŋu atrɔ kpekpe siwo míewɔna ƒe xexlẽme eye. woƒe ɣeyiɣi si sɔ ɖe nutoa me ƒe nuhiahiãwo nu, d) wona kpekpewɔƒewo kple nusiwo katã woatsɔ awɔ kpekpeawoe la mí tso habɔbɔ si le dɔ wɔm gbɔ, e) míaƒe dɔa sɔ (womele mɔ kpɔm be míazɔ kɔƒe geɖe alo didiƒe ŋutɔ alo awɔ kpekpe geɖe akpa o )",
"Míexɔa kpekpeɖeŋu le nuto siawo dometɔ etɔ̃ me a) míexɔa hehe edziedzi (menye zi ɖeka o) le míaƒe nutoa me gbe me, b) míenya nusi wɔm míele kple nusita wòle vevie, c) míate ŋu atrɔ kpekpe siwo míewɔna ƒe xexlẽme eye. woƒe ɣeyiɣi si sɔ ɖe nutoa me ƒe nuhiahiãwo nu, d) wona kpekpewɔƒewo kple nusiwo katã woatsɔ awɔ kpekpeawoe la mí tso habɔbɔ si le dɔ wɔm gbɔ, e) míaƒe dɔa sɔ (womele mɔ kpɔm be míazɔ kɔƒe geɖe alo didiƒe ŋutɔ alo awɔ kpekpe geɖe akpa o )",
"Míexɔa kpekpeɖeŋu le nuto siawo KAtã me a) míexɔa hehe edziedzi (menye zi ɖeka o) le míaƒe nutoa me gbe me,b) míenya nusi wɔm míele kple nusita wòle vevie, c) míate ŋu atrɔ kpekpe siwo míewɔna ƒe xexlẽme kple woƒe ɣeyiɣi be wòasɔ ɖe nutoa me ƒe nuhiahiãwo nu, d) wona kpekpewɔƒewo kple nusiwo katã woatsɔ awɔ kpekpeawoe la mí to dɔdzikpɔlawo dzi habɔbɔ, e) míaƒe dɔa sɔ (womele mɔ kpɔm be míazɔ kɔƒe geɖe alo didi ŋutɔ alo awɔ kpekpe geɖe akpa o)"]
}