const basics={
    h1:"Informations sur le Programme",
    figure1:"Figure ",
    figure2:" de 5. Cliquez sur la flèche pour le graphique suivant",
    program:"Nom du programme",
    organization:"Nom de l'organisation (si différent du nom du programme)",
    orgtype:"Type d'organisation:",
    country:"Le(s) pays de programmation",
    region:"Provinces / Région (le cas échéant)",
    name:"Qui réalise cette évaluation ? Nom (s)",
    date:"Date d'exécution",
    stage: "Stade de travail",
    save:"Sauvegarder les données",
    sendmail:"Envoyer les données par e-mail",
    comment:"Commentaire"
};

const stages=["pilote","nouveau", "à mi-parcous", "mature", "terminé"];
const orgtypes=["Gouvernement local/affilié au gouvernement","organisation à but non lucratif/de la société civile."];
const clickto="Cliquez pour enregistrer le commentaire";
const comment="Commentaire";

const dimensions=[
"A: Participation, Inclusion, et Voix",
"B: Ressources et Connaissances Locales",
"C: La Durabilité",
"D: Mécanismes de Redevabilité",
"E: Réactivité aux Dynamiques Spécifiques au Contexte",
"F: Collaboration au sein et entre les communautés",
"G: Travailler avec la société civile/le gouvernement local",
"H: Les Pratiques de Suivi et d'Évaluation qui Soutiennent le DPC",
"I: Inventissement et Intensité de Facilitation"
];
const rubric={
    p2:["A1. Le programme assure l'inclusion de tous les groupes de personnes dans la communauté (comme les vieux et les jeunes, les hommes et les femmes, les aisés et les pauvres, de différents clans, castes, religions, etc.)",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne tient pas compte des différents groupes de personnes qui vivent dans un village.",
    "Le programme considère certains groupes exclus (pas tous) et assure leur participation aux réunions/activités collectives.",
    "Le programme considère la plupart des groupes de personnes et assure leur participation aux réunions/activités collectives.",
    "Le programme considère tous les groupes de personnes, assure leur participation active aux réunions/activités collectives."],
    p3:["A2. Les membres de la communauté décident des priorités du programme CLD AVANT la conception même du programme.",
    "Je ne sais pas/informations insuffisantes",
    "Les membres de la communauté ne sont pas impliqués dans la décision des priorités du programme.",
    "Certains membres de la communauté (par exemple, les chefs traditionnels, les propriétaires fonciers, etc.) ou des groupes sont impliqués dans la décision des priorités du programme.",
    "La plupart des groupes communautaires sont impliqués dans le choix des priorités du programme.",
    "Tous les groupes communautaires sont impliqués dans la décision des priorités du programme et y ont une voix égale."],
    p4:["A3. Les membres de la communauté jouent un rôle actif dans la planification du programme CLD dans leur communauté.",
    "Je ne sais pas/informations insuffisantes",
    "Les membres de la communauté ne participent pas au processus de planification.",
    "Certains membres de la communauté (par exemple, les chefs traditionnels, les propriétaires fonciers, etc.) ou des groupes participent au processus de planification.",
    "La plupart des groupes communautaires participent au processus de planification.",
    "Tous les groupes communautaires participent au processus de planification et y ont une voix égale."],
    p5:["A4. Les organismes communautaires représentant tous les groupes et quartiers mettent en œuvre le programme.",
    "Je ne sais pas/informations insuffisantes",
    "Les ONG ou les dirigeants locaux existants mettent en œuvre le programme.",
    "Les ONG et/ou les dirigeants locaux créent un organisme qui mettra en œuvre le programme ou travaillera avec un organisme existant qui peut ne pas inclure des membres de tous les groupes.",
    "Des organismes avec des membres auto-désignés représentant tous les groupes et quartiers mettent en œuvre le programme.",
    "Des instances élues représentant tous les groupes et quartiers mettent en œuvre le programme."],
    p6:["A5. Le programme renforce la voix et la confiance des représentants de la communauté pour influencer/façonner la prise de décision.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne fait aucun effort pour renforcer la voix ou la confiance des représentants de la communauté.",
    "Le programme renforce la voix et la confiance parmi certains représentants de la communauté, mais pas ceux des groupes exclus.",
    "Le programme renforce la voix et la confiance de nombreux représentants de la communauté, y compris ceux de certains groupes exclus.",
    "Le programme renforce la voix et la confiance parmi tous les représentants de la communauté, y compris ceux de tous les groupes exclus."],
    p7:["A6. Le programme sensibilise aux droits (sociaux, économiques et politiques) et renforce les compétences des représentants locaux pour demander ces droits.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne sensibilise pas et ne renforce pas les compétences pour demander des droits.",
    "Le programme sensibilise aux droits, mais ne développe aucune compétence pour les revendiquer.",
    "Le programme sensibilise aux droits et renforce les compétences de quelques personnes pour les demander.",
    "Le programme sensibilise aux droits et se concentre sur le renforcement des compétences des représentants locaux de tous les groupes pour les revendiquer."],
    p8:["B1. Le programme CLD s'appuie sur les ressources et connaissances locales.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne tient pas compte des ressources et des connaissances locales.",
    "Le programme explore les ressources locales, mais les connaissances extérieures sont transmises par le personnel de première ligne.",
    "Le programme utilise les ressources locales et est conscient des connaissances locales.",
    "Le programme utilise et respecte les connaissances et les ressources locales."],
    p9:["B2. La communauté apporte ses ressources (par exemple, temps, argent, main-d'œuvre, terres, matériaux, etc.)",
    "Je ne sais pas/informations insuffisantes",
    "Les membres de la communauté ne contribuent pas à la mise en œuvre du programme en espèces, en nature ou en main-d'œuvre.",
    "Les membres de la communauté contribuent en temps/travail ou en ressources (terre, argent, matériaux) parce que c'est obligatoire.",
    "Les membres de la communauté contribuent en temps/travail ou en ressources (terre, argent, matériaux), lorsqu'ils y sont encouragés.",
    "Les membres de la communauté décident de ce qui est nécessaire, identifient volontairement des ressources supplémentaires (temps/travail, terres, argent, matériaux) et les proposent."],
    p10:["C1. Les communautés sont essentielles pour planifier comment et quand le programme doit être achevé et leur être remis.",
    "Je ne sais pas/informations insuffisantes",
    "Il n'y a aucun plan pour l'achèvement et le transfert du programme.",
    "Le plan d'achèvement et de transfert du programme est créé par l'organisation de mise en œuvre et les dirigeants communautaires ou les membres de la communauté en sont informés.",
    "Le plan d'achèvement et de transfert du programme est créé en consultation avec les dirigeants locaux et les membres de la communauté.",
    "Le plan d'achèvement et de transfert du programme est dirigé par les membres de la communauté et dirigeants locaux."],
    p11:["C2. Les communautés travaillent avec les organisations de mise en œuvre pour revoir et adapter en permanence la planification du transfert des programmes et de la transition",
    "Je ne sais pas/informations insuffisantes",
    "Il n'y a pas de plan ou de stratégie pour que votre organisation transmette les programmes à la communauté",
    "Les plans de transfert du programme à la communauté ne sont faits que lorsque le programme touche à sa fin (ou qu'il ne reste plus de financement)",
    "Les plans de passation du programme à la communauté sont faits en début de programme et révisés en fin de programme ou en cas de contretemps majeur",
    "Les plans de transfert du programme à la communauté sont élaborés au début du programme et sont régulièrement revus avec les membres de la communauté pour refléter la situation actuelle dans la communauté"],
    p12: ["C3. Le programme garantit que les structures communautaires (comme les organisations communautaires, les groupes mettant en œuvre des programmes) ont les capacités de continuer à travailler après le transfert",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne fait aucun effort pour assurer la capacité des structures communautaires à continuer à travailler après la passation.",
    "Il existe un plan pour le transfert du programme, mais aucune stratégie pour garantir que les structures communautaires puissent continuer à travailler après le transfert et avoir les capacités d'obtenir des financements/ressources (au besoin).",
    "Il existe une stratégie pour s'assurer que les structures communautaires peuvent continuer à fonctionner après le transfert, mais il n'y a pas d'activités pour développer les capacités pour obtenir des financements/ressources (au besoin).",
    "Le programme met en œuvre des activités pour renforcer les capacités afin de garantir que les structures communautaires puissent continuer à fonctionner après le transfert et obtenir des financements/ressources (au besoin)."],
    p13:["C4. Une fois terminé, l\'impact du programme est mesuré avec la participation locale.",
    "Je ne sais pas/informations insuffisantes",
    "Il n'y a aucun plan pour mesurer l'impact du programme après l'achèvement ou la communauté ne sait pas s'il y a des plans.",
    "Il existe des plans pour mesurer l'impact du programme (ou il est mesuré) après l'achèvement. Les membres de la communauté sont informés de l'exercice et fournissent les informations demandées.",
    "L'impact est mesuré (ou prévu d'être mesuré) après l'achèvement du programme et les membres de la communauté sont consultés dans le cadre de l'exercice.",
    "L'impact est mesuré (ou prévu pour être mesuré) après l'achèvement du programme et les membres de la communauté sont des participants actifs à toutes les étapes de l'exercice."],
    p14: ["C5. Après le transfert du programme aux structures gouvernementales communautaires/locales, les membres de la communauté appartenant à tous les groupes (par exemple, les femmes, les jeunes, les personnes âgées, les pauvres, les personnes handicapées, les minorités) bénéficient toujours des activités menées par la communauté .",
    "Je ne sais pas/informations insuffisantes",
    "Personne ne bénéficie d'avantages après le transfert du programme ou seuls les groupes privilégiés continuent d'en bénéficier.",
    "Le programme continue de bénéficier à certains groupes même après la passation.",
    "Le programme continue de bénéficier à la plupart des groupes même après le transfert.",
    "Le programme continue de bénéficier à tous les groupes même après la passation."],
    p15:["D1. Le programme et les structures communautaires partagent des informations importantes, par exemple ce qu'ils font, pourquoi, comment et comment les fonds ont été utilisés.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne partage aucune information sur ce qui est fait, comment et pourquoi avec la communauté.",
    "Le programme ou les organismes communautaires partagent parfois des informations de base autour du programme mais la plupart des détails ne sont pas disponibles.",
    "Le programme ou les organismes communautaires partagent souvent des informations autour du programme (la plupart mais pas toutes les informations sont disponibles).",
    "Les organismes du programme et de la communauté partagent régulièrement des informations sur les fonds, les processus et les activités avec les membres de la communauté et invitent les commentaires."],
    p16:["D2. Le programme répond aux doléances/plaintes de la communauté.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme n'offre aucun moyen aux membres de la communauté de soulever des griefs ou des plaintes.",
    "Le programme permet aux membres de la communauté de soulever des griefs/plaintes, mais il n'est ni accessible ni digne de confiance.",
    "Le programme offre aux membres de la communauté un moyen accessible et fiable de soulever des griefs/plaintes, mais les plaintes ne sont pas traitées.",
    "Le programme a un moyen accessible et fiable pour les membres de la communauté de soulever des griefs/plaintes, les plaintes sont traitées."],
    p17:["D3. Les résultats du suivi et de l'évaluation sont régulièrement partagés avec les membres de la communauté.",
    "Je ne sais pas/informations insuffisantes",
    "Les résultats du suivi et de l'évaluation ne sont jamais partagés avec les membres de la communauté.",
    "Les résultats du suivi et de l'évaluation peuvent être partagés avec les membres de la communauté par les personnes impliquées dans le programme quand elles en ont envie.",
    "Les résultats du suivi et de l'évaluation ne sont partagés avec les membres de la communauté que lorsque des problèmes surviennent.",
    "Les résultats du suivi et de l'évaluation sont régulièrement partagés avec les membres de la communauté."],
    p18:["E1. Le programme est sensible à l'évolution des besoins et des contextes communautaires.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne répond pas à l'évolution de la communauté besoins de santé (par exemple, les inondations, les sécheresses, la faim saisonnière, l'arrivée de nouvelles technologies, les changements de systèmes politiques, etc.) ",
    "Le programme est capable d'apporter quelques modifications.",
    "Le programme est capable de s'adapter au besoin aux besoins changeants de la communauté, y compris ceux provoqués par des crises ou des catastrophes.",
    "Le programme est capable de s'adapter aux besoins changeants de la communauté, y compris ceux provoqués par des crises ou des catastrophes, et met en place des mécanismes/structures pour faire face à des situations similaires à l'avenir."],
    p19:["E2. Le rythme du programme CLD (c'est-à-dire le moment, la fréquence et la durée de l'engagement avec la communauté) est déterminé avec les membres de la communauté.",
    "Je ne sais pas/informations insuffisantes",
    "La communauté n'est pas impliquée dans la décision du rythme du programme.",
    "La communauté est informée du rythme du programme.",
    "Certains membres de la communauté sont consultés pour décider du rythme du programme.",
    "Tous les membres de la communauté, y compris les représentants des groupes marginalisés, sont consultés pour décider du rythme du programme."],
    p20:["F1. Le programme établit des relations positives entre les riches et les pauvres ; les pauvres et les pauvres.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne tient pas compte des différences économiques.",
    "Le programme établit des relations entre les pauvres et les pauvres.",
    "Le programme engage les riches et les pauvres dans des discussions et un dialogue.",
    "Le programme engage les riches et les pauvres à travailler ensemble pour atteindre un objectif commun."],
    p21:["F2. Le programme établit des relations positives au sein des mêmes groupes et entre différents groupes ethniques, de caste, religieux, etc.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne tient pas compte des différences de caste/ethnique/religieuse.",
    "Le programme construit des relations entre les personnes de la même caste/ethnie/religion pour travailler ensemble pour le changement social.",
    "Le programme engage des personnes de différentes castes/ethnies/religions dans des discussions et un dialogue.",
    "Le programme établit des relations entre des personnes de différentes castes/ethnies/religions pour travailler ensemble pour le changement social."],
    p22:["F3. Le programme construit des relations positives entre les femmes et les femmes et, entre les hommes et les femmes.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne fonctionne pas avec les femmes.",
    "Le programme construit des relations entre les femmes du même groupe.",
    "Le programme établit des relations entre tous les groupes de femmes OU entre les femmes et les hommes.",
    "Le programme établit des relations entre tous les groupes de femmes ET entre les femmes et les hommes."],
    p23:["F4. Le programme relie les communautés locales ou leurs dirigeants à d'autres villages et leurs dirigeants à travers les districts, les provinces ou les états.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ne crée pas de réseaux et de liens communautaires.",
    "Le programme crée des liens entre les communautés/dirigeants locaux d'un même district.",
    "Le programme établit des liens entre les communautés/les dirigeants locaux à travers le district/l'état/la province/le pays.",
    "Le programme établit des liens entre les communautés à travers les espaces étatiques / régionaux / nationaux pour une action collective."],
    p24:["G1. Les groupes communautaires du programme travaillent en collaboration avec les structures et les acteurs du gouvernement local.",
    "Je ne sais pas/informations insuffisantes",
    "Le programme ou ses groupes communautaires et les structures et acteurs gouvernementaux locaux pertinents existants donnent des informations/messages contradictoires.",
    "Le programme ou ses groupes communautaires et les structures et acteurs gouvernementaux locaux pertinents existants ne travaillent pas du tout ensemble (même lorsqu'ils travaillent vers les mêmes objectifs).",
    "Le programme ou ses groupes communautaires et les structures et acteurs gouvernementaux locaux concernés travaillent parfois ensemble sur certaines questions.",
    "Le programme et ses groupes communautaires et structures/acteurs gouvernementaux locaux travaillent régulièrement ensemble et se complètent."],
    p25:["H1. Les membres de la communauté surveillent les activités clés et les progrès du programme.",
    "Je ne sais pas/informations insuffisantes",
    "Il n'y a pas de suivi participatif communautaire.",
    "La surveillance communautaire se produit parfois.",
    "La surveillance communautaire a lieu régulièrement, mais est facilitée par le personnel de première ligne.",
    "Le suivi communautaire a lieu régulièrement et est facilité par les membres ou les structures de la communauté."],
    p26:["H2. L'évaluation participative est réalisée.",
    "Je ne sais pas/informations insuffisantes",
    "Il n'y a pas d'évaluation participative communautaire.",
    "Les membres de la communauté sont impliqués dans UNE ou DEUX de ces activités: 1) Planification ; 2) Collecte de données ; 3) Analyse ; 4) Validation ; 5) Conclusions et recommandations ; 6) Planification d'action.",
    "Les membres de la communauté sont impliqués dans plusieurs (TROIS ou QUATRE) de ces activités: 1) Planification ; 2) Collecte de données ; 3) Analyse ; 4) Validation ; 5) Conclusions et recommandations ; 6) Planification d'action.",
    "Les membres de la communauté sont au centre de TOUTES les activités: 1) Planification ; 2) Collecte de données ; 3) Analyse ; 4) Validation ; 5) Conclusions et recommandations ; 6) Planification des actions. "],
    p27:["H3. Les activités de suivi et d'évaluation examinent comment le programme fonctionne avec et profite à différents groupes de personnes, y compris les femmes, les personnes handicapées , les personnes âgées, les personnes issues de minorités.",
    "Je ne sais pas/informations insuffisantes",
    "Les membres de la communauté ne savent pas parce qu'ils ne sont pas impliqués dans le suivi et l'évaluation (S&E) OU les membres de la communauté sont impliqués mais les systèmes de S&E ne tiennent pas compte des différents groupes de personnes lors de la collecte ou de l'analyse des informations.",
    "Le suivi et l'évaluation collectent et analysent des informations pour comprendre comment le programme fonctionne avec et profite à certains groupes de la communauté (par exemple, les hommes et les femmes, mais pas les personnes handicapées).",
    "Le suivi et l'évaluation collectent et analysent des informations pour comprendre comment le programme fonctionne avec et profite à la plupart des groupes de la communauté.",
    "Le suivi et l'évaluation collectent et analysent des informations pour comprendre comment et pourquoi le programme fonctionne avec et profite à tous les différents groupes de personnes."],
    p28:["I1. Les animateurs décident de l'heure, du lieu et du cadre des réunions de manière à ce que tout le monde puisse y participer.",
    "Je ne sais pas/informations insuffisantes",
    "Les animateurs décident de l'heure, du lieu et du cadre des réunions en fonction de leur propre convenance ou de celle de quelques privilégiés dans la communauté.",
    "Les animateurs rencontrent au moins l'un des éléments suivants: organisez des réunions à un moment, un lieu ou un cadre permettant à toutes les personnes de participer et de parler librement.",
    "Les animateurs respectent au moins deux des éléments suivants: organisez des réunions à une heure, dans un lieu et dans un cadre qui permettent à tous de participer et de parler librement.",
    "Les animateurs remplissent les trois conditions suivantes: organisez des réunions à une heure, dans un lieu et dans un cadre qui permettent à toutes les personnes de participer et de parler librement."],
    p29:["I2. Les facilitateurs de projet sont respectueux et encouragent le dialogue.",
    "Je ne sais pas/informations insuffisantes",
    "Les animateurs sermonnent et disent aux gens quoi faire, n'écoutent pas et sont irrespectueux.",
    "Les animateurs écoutent et traitent les gens avec respect.",
    "Les animateurs écoutent leurs idées, traitent les gens avec respect et encouragent tous les participants à parler.",
    "Les animateurs écoutent, traitent les gens avec respect et encouragent les gens à se parler."],
    p30:["I3. Après avoir assisté aux réunions avec les animateurs, nous avons le sentiment: ",
    "Je ne sais pas/informations insuffisantes",
    "C'était une perte de temps ; nous n'y assistons que parce que nous y sommes obligés.",
    "Nous entendons de nouvelles idées mais ne savons pas quoi en faire.",
    "Nous entendons de nouvelles idées et les animateurs nous disent comment les mettre en pratique.",
    "Nous entendons de nouvelles idées et apprentissages et décidons collectivement comment agir en conséquence."],
    p31: ["I4. (Pour les facilitateurs uniquement) Nous nous sentons soutenus (recevons des formations régulières, comprenons ce que nous faisons et pourquoi, avons de la flexibilité et des budgets) par l'organisation de mise en œuvre/l'agence gouvernementale pour faire notre travail",
    "Je ne sais pas/informations insuffisantes",
    "L'organisation de mise en œuvre/l'agence gouvernementale ne fait aucun effort pour soutenir notre travail",
    "Nous recevons un soutien dans deux de ces domaines a) nous recevons une formation régulièrement (pas une seule fois) dans notre langue locale, b) nous savons ce que nous faisons et pourquoi c'est important, c) nous pouvons modifier le nombre de réunions que nous facilitons et leur calendrier pour répondre aux besoins locaux, d) l'organisation de mise en œuvre nous fournit des espaces de réunion et tout le matériel nécessaire pour organiser les réunions, e) notre charge de travail est raisonnable (ne devrait pas couvrir trop de villages ou de très longues distances ou faire trop de réunions )",
    "Nous recevons un soutien dans trois de ces domaines a) nous recevons une formation régulièrement (pas une seule fois) dans notre langue locale, b) nous savons ce que nous faisons et pourquoi c'est important, c) nous pouvons modifier le nombre de réunions que nous facilitons et leur calendrier pour répondre aux besoins locaux, d) l'organisation de mise en œuvre nous fournit des espaces de réunion et tout le matériel nécessaire pour organiser les réunions, e) notre charge de travail est raisonnable (ne devrait pas couvrir trop de villages ou de très longues distances ou faire trop de réunions )",
    "Nous recevons un soutien dans TOUS ces domaines a) nous recevons une formation régulièrement (pas une seule fois) dans notre langue locale, b) nous savons ce que nous faisons et pourquoi c'est important, c) nous pouvons modifier le nombre de réunions que nous facilitons et leur calendrier pour répondre aux besoins locaux, d) l'organisation de mise en œuvre nous fournit des espaces de réunion et tout le matériel nécessaire pour organiser les réunions, e) notre charge de travail est raisonnable (ne devrait pas couvrir trop de villages ou de très longues distances ou faire trop de réunions )"]
}