const basics={
    figure1:"Chithunzi ",
    figure2:" mwa 5. Dinani mivi kuti mupeze zotsatira zambiri.",
    h1:"Chiyambi",
    program:"Dzina la pulojekiti",
    organization:"Dzina la bungwe (ngati ndi losiyana ndi dzina la pulojekiti)",
    orgtype:"Type of organization:",
    country:"Dziko/mayiko komwe pulojekiti ikuchitikira:	",
    region:"Chigawo/Dera lomwe tiri (ngati ziliko)",
    name:"Akutsogolera kugwiritsa ntchito chipangizochi ndi ndani?",
    date:"Tsiku lomwe tamaliza kugwiritsa ntchito chipangizochi",
    stage:"Nthawi/gawo la pulojekiti",
    save:"Sungani deta",
    sendmail:"Imelo za data",
    comment:"Ndemanga kapena zina ndi zina zotumphukira"
}
const stages=['zongoyesera','zatsopano','mkati mwa ndime','zokhwima','zomalizitsa'];
const orgtypes=["Zamaboma ang'ono/Zokhudzana ndi Boma","Mabungwe ongothandiza/ Mabungwe otumikira anthu"];

const clickto="Dinani kuti musunge ndemanga";
const comment="Ndemanga";

const dimensions=[
"A: Kutengapo mbali, Kuphatikizidwa, ndi Mawu",
"B: Zipangizo Zam'deralo ndi Chidziwitso",
"C: Kukhazikika ndi Njira Yosinthanirana Zinthu",
"D: Njira Zowerengera",
"E: Kuyankhapo pa zochitika",
"F: Mgwirizano",
"G: Kugwira ntchito ndi maboma ang'ono/ mabungwe otumikira anthu",
"H. Kuyang'anira ndi Kuwunika",
"I. Kuwongolera"];

const rubric={
p2:["A1. Pulogalamuyi imawonetsetsa kuphatikizidwa kwa magulu onse a anthu am'mudzi (monga achikulire ndi achinyamata, amuna ndi akazi, olemera ndi osauka, ochokera m'mafuko osiyanasiyana, magulu, zipembedzo, ndi zina zotero.)",
"Sindikudziwa / uthengawu ngosakwanira",
"Pulogalamuyi siyiganizira zamagulu osiyanasiyana a anthu omwe amakhala kumudzi.",
"Pulogalamuyi imayang'ana magulu osasankhidwa (osati onse) ndikuwonetsetsa kuti akutenga nawo gawo pamisonkhano/zochitira limodzi,",
"Pulogalamuyi imaganizira magulu ambiri a anthu ndikuwonetsetsa kuti akutengapo nawo mbali pamisonkhano/zochitira limodzi.",
"Pulogalamuyi imaganizira magulu onse a anthu, ndikuwonetsetsa kuti akutengapo  nawo mbali pamisonkhano/zochitira limodzi."],
p3:["A2. Anthu am'mudzi amasankha zofunikira za pulogalamu ya CLD kupanga kwenikweni kwa pulogilamu kusanachitike.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Anthu a m'mudzi satenga nawo mbali posankha zofunikira pa pulogalamuyi.",
"Sankhani  anthu  a m'mudzi (mafumu, eni minda, ndi ena otero) kapena magulu omwe akutenga nawo mbali posankha zofunikira za pulogalamuyi.",
"Magulu ambiri am'mudzi amatenga nawo mbali posankha zofunikira za  pulogalamu.",
"Magulu onse am'mudzi amatenga nawo  mbali posankha zofunikira za pulogalamuyi ndipo ali ndi mawu ofanana pankhaniyi."],
p4:["A3. Anthu am'mudzi amatenga nawo mbali yayikulu pakukonzekera mapulogalamu a CLD mdera lawo.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Anthu ammudzi satenga nawo mbali pokonzekera za pulogalamuyi.",
"Kusankha anthu ammudzi (monga atsogoleri, eni minda, ndi zina zotero) kapena magulu atenge nawo mbali pokonzekera pulogalamu.",
"Magulu ambiri ammudzi amatenga nawo mbali pokonzekerazi.",
"Magulu onse ammudzi amatenga nawo mbali pakukonzekera ndondomekoyi ndipo maganizo awo amatengedwa mofanana."],
p5:["A4. Mabungwe ammudzi omwe akuyimira magulu onse ndi oyandikana nawo akuyendetsa pulogalamuyi.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Mabungwe omwe siaboma kapena atsogoleri omwe alipo amayendetsa pulogalamuyi.",
"Mabungwe omwe siaboma kapena atsogoleri amdera (kapena mogwirizana awiriwa) amapanga bungwe lomwe liyendetse ntchito za pulogalamuyo kapena kugwira ntchito ndi bungwe lomwe lilipo lomwe silingaphatikizepo athu kuchoka amagulu onse.",
"Mabungwe awanthu oziyika mumaudindo okha omwe akuimira magulu  ndi madera onse akuyendetsa pulogalamuyi.",
"Mabungwe osankhidwa omwe akuimira magulu onse mdela akuyendetsa pulogalamuyi."],
p6:["A5. Pulogalamuyi imapangisa kuthekera koikapo mulomo kwa oyimirila anthu ammudzi pa zochitika.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi sichita khama polimbikitsa mawu kapena luntha la oyimilira am'mudzi.",
"Pulogalamuyi imapanga mawu ndi chidaliro pakati pa oyimira anthu ena, koma osati omwe amachokera m'magulu osasankhidwa.",
"Pulogalamuyi imalimbikitsa mawu ndi luntha  pakati pa oyimilira am'mudzi ambiri kuphatikizanso ochokera m'magulu ena osasankhidwa.",
"Pulogalamuyi imalimbikitsa  mawu ndi luntha  pakati pa onse oyimira anthu am'mudzi kuphatikizapo  omwe amachokera m'magulu onse osasankhidwa."],
p7:["A6. Pulogalamuyi imalimbikitsa kuzindikira za maufulu (zachikhalidwe, zachuma ndi ndale) ndikumanga luso pakati pa oimira m'deralo kuti afunse za maufuluwo.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi siyikulitsa chidziwitso ndikumanga luso lofunsa  za maufulu.",
"Pulogalamuyi imalimbikitsa kuzindikira za maufulu, koma siimanga  luso lirilonse lomafunsa za maufuluwo",
"Pulogalamuyi imalimbikitsa kuzindikira za maufulu, ndipo imamanga luso kwa anthu ochepa kuti awafunse.",
"Pulogalamuyi imalimbikitsa anthu kudziwa za maufulu, ndipo imayang'ana kwambiri pakupereka  maluso pakati pa oyimilira amderalo ochokera m'magulu onse kuti awafunse."],
p8:["B1.Pulogalamu ya CLD imamanga pa Local Resources ndi Knowledge.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi siyiganizira zazinthu za m'deralo komanso chidziwitso.",
"Pulogalamuyi imafunafuna  zinthu zomwe zili m'deralo komanso chidziwitso. Komabe imadalira chidziwitso chakunja chofalitsidwa ndi otsogolera pulogilamuyo.",
"Pulogalamuyi imagwiritsa ntchito zinthu za m'deralo komanso chidziwitso cha komweko momwe ikufunira.",
"Pulogalamuyi imagwiritsa ntchito ndikulemekeza chidziwitso ndi zinthu zomwe zili m'deralo. Imadalira zimenezo"],
p9:["B2. Anthu am'mudzi amapereka chuma chawo (monga nthawi, ndalama, ntchito, malo, zipangizo, chikoka, etc.)",
"Sindikudziwa/ uthengawu ngosakwanira",
"Anthu am'mudzi sachitapo kanthu pakayendetsedwe ka  pulogalamuyo m'njira ya  ndalama kapena zachifundo kapena ntchito.",
"Anthu am'mudzi amapereka nthawi/ntchito kapena chuma (nthaka, ndalama, zipangizo) chifukwa ndi zovomerezeka.",
"Anthu am'mudzi amapereka nthawi/ntchito kapena chuma (malo, ndalama, zipangizo), akalimbikitsidwa.",
"Anthu am'mudzi amasankha zomwe zikufunika, mosakakamizika amapeza  zofunika zoonjezera (nthawi/ntchito, malo, ndalama, zipangizo) ndikupereka mwaulere."],
p10:["C1. Madera ndi ofunika kwambiri pokonzekera momwe ndi nthawi yomwe pulogalamuyo idzamalizidwe ndikuperekedwa kwa iwo.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Palibe ndondomeko yomalizitsa ndi kupereka pulogilamu",
"Dongosolo lomaliza ndi kuperekedwa kwa pulogalamuyo limapangidwa ndi bungwe lomwe likugwira ntchitoyo ndi atsogoleri am'mudzi kapena anthu am'mudzi amadziwitsidwa za izi.",
"Dongosolo lomaliza ndi kuperekedwa kwa pulogilamu limapangidwa mogwirizana ndi atsogoleri amderalo ndi anthu am'mudzi.",
"Dongosolo lomaliza ndi kuperekedwa kwa pulogilamu  limatsogozedwa ndi anthu am'mudzi ndi atsogoleri amderalo."],
p11:["C2. Madera amagwira ntchito limodzi ndi mabungwe omwe akuyendetsa  ntchito  kuti aziwunika pafupipafupi ndi kuzolowera   ndondomeko ya kaperekedwere ka mapulogilamu ndi kusintha",
"Sindikudziwa/ uthengawu ngosakwanira",
"Palibe ndondomeko kapena njira yoti bungwe lipereke mapulogalamuwa kwa anthu am'mudzi",
"Mapulani opereka pulogalamuyi kwa anthu am'mudzi amapangidwa pokhapokha pulogalamuyo ikamayandikira kwakutha  (kapena palibe ndalama zomwe zatsala)",
"Mapulani opereka pulogalamuyi kwa anthu am'mudzi amapangidwa kumayambiriro kwa pulogalamuyo ndikukonzedwanso kumapeto kwa pulogalamuyo kapena ngati pali vuto lalikulu",
"Mapulani opereka pulogalamuyi kwa anthu am'mudzi amapangidwa kumayambiriro kwa ndondomekoyi ndipo amawunikiridwa nthawi zonse ndi anthu am'mudzi kuti awonetsere momwe zinthu zilili panthawiyo m'deralo"],
p12:["C3. Pulogalamuyi imawonetsetsa kuti magulu a anthu mderalo (monga mabungwe am'mudzi, magulu omwe akukhazikitsa mapologalamu) ali ndi kuthekera kopitiliza kugwira ntchito ikaperekedwa",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi sichita khama kuwonetsetsa kuti magulu am'mudzi ali ndi kuthekera kopitiliza  kugwira ntchito pambuyo poperekedwa.",
"Pali ndondomeko yoperekera pologalamu koma palibe njira yowonetsetsa kuti magulu a anthu am'mudzi atha kupitiliza  kugwira ntchito pambuyo popereka ndikuti ali ndi kuthekera kopeza ndalama  / zothandizira (monga kufunikira)",
"Pali njira yowonetsetsa kuti magulu am'mudzi athe kupitiliza  kugwira ntchito itaperekedwa koma palibe zochitika kukhala ndi kuthekera   kopeza ndalama / zothandizira (monga kufunikira).",
"Pulogalamuyi ikugwira ntchito zolimbikitsa anthu kukhala ndi kuthekera powonetsetsa kuti magulu am'mudzi athe kupitiliza  kugwira ntchito itaperekedwa ndikupeza ndalama / zothandizira (monga momwe zingafunikire)."],
p13:["C4. Ikamalizika, zotsatira za  pulogalamuyo zimayezedwa potengapo gawo anthu amdera.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Palibe ndondomeko yoyezera zotsatira za pulogalamu ikamalizidwa kapena anthu sakudziwa ngati pali mapulani ena alionse.", 
"Pali mapulani oyezera zotsatira za pulogalamu (kapena imayezedwa) ikamalizidwa. Anthu am'mudzi amadziwitsidwa za ntchitoyi ndikupereka mayankho molingana ndi m'mene afunsidwira.",
"Zotsatira zimayezedwa (kapena kulinganizidwa kuti ziyezedwe) pulogalamu ikatha ndipo anthu am'mudzi afunsidwa pazochitikazo.",
"Zotsatira zimayezedwa (kapena kulinganizidwa kuti ziyezedwe) pulogalamu ikatha ndipo anthu am'mudzi amakhala otenga nawo mbali mu magawo onse a ntchitoyi."],
p14:["C5. Pologalam itaperekedwa kwa anthu am'mudzi/magulu a maboma ang'ono/ anthu a m'magulu onse (monga amayi, achinyamata, okalamba, osauka, olumala, anthu ochepa) amapindulabe ndi ntchito zotsogozedwa ndi anthu. ",
"Sindikudziwa/ uthengawu ngosakwanira",
"Palibe amene amapeza phindu liri lonse   pulogalamu ikaperekedwa kapena kupatula magulu omwe ali ndi mwayi amapitilirabe kupindula.",
"Pulogalamuyi imapitilizabe kupindulitsa magulu ena ngakhale itaperekedwa.",
"Pulogalamuyi imapitilizabe kupindulitsa magulu ambiri ngakhale itaperekedwa.",
"Pulogalamuyi imapitilizabe kupindulitsa magulu onse, makamaka omwe ali pachiwopsezo kwambiri, ngakhale itaperekedwa.."],
p15:["D1. Pologalamu ndi magulu am'mudzi amagawana zambiri  mwachitsanzo zomwe akuchita, chifukwa chiyani, m'mene akuchira, ndi momwe ndalama zinagwiritsidwira ntchito.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi sigawana ndi anthu am'mudzi china chiri chonse pa  zomwe zikuchitika, m'mene chikuchitikira  ndi chifukwa chake.",
"Pulogalamu kapena mabungwe am'mudzi nthawi zina amagawana pang'ono zokhudzana ndi pulogalamuyi koma tsatanetsatane wa zambiri samapezeka.",
"Pulogalamuyo kapena mabungwe am'mudzi nthawi zambiri amagawana  zokhudzana ndi pulogalamuyi (zambiri koma si zonse zofunikira zomwe zimapezeka).",
"Pologalamu ndi mabungwe am'mudzi kawiri-kawiri amagawana  zokhudzana ndi ndalama, ndondomeko, ndi zochitika ndi anthu am'mudzi ndikuyitanitsa ndemanga."],
p16:["D2. Pulogalamuyi imayankha madandaulo a anthu am'mudzi/madandaulo a anthu.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi ilibe njira iliyonse yoti anthu am'mudzi anene  zokhumudwitsa  kapena madandaulo.",
"Pulogalamuyi ili ndi njira yoti anthu am'mudzi anene  zokhumudwitsa /madandaulo, koma siimapezeka kapena kudalilika.",
"Pulogalamuyi ili ndi njira yofikirika komanso yodalirika kuti anthu am'mudzi azinena zokhumudwitsa /madandaulo, koma madandaulo sayankhidwa.",
"Pulogalamuyi ili ndi njira yofikirika komanso yodalirika kuti anthu ammudzi azinena zokhumudwitsa /madandaulo ndipo madandaulo amayankhidwa."],
p17:["D3. Zotsatira za kuyang'anira  ndi kuwunika zimagawidwa nthawi zonse ndi anthu am'mudzi.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Zotsatira za Kuyang'anira ndi kuunika sizimagawidwa ndi anthu ammudzi.",
"Zotsatira kuchokera ku ntchito  ya Kuyang'anira ndi  Kuunika zitha kugawidwa ndi anthu am'mudzi ndi anthu omwe ali nawo mu pulogalamuyi atafuna kutero.",
"Zotsatira zochokera ku ntchito ya  Kuyang'anira ndi kuunika zimagawidwa ndi anthu am'mudzi pokhapokha pakabuka mavuto.",
"Zotsatira zochokera ku  Kuyang'anira ndi kuunika zimagawidwa pafupipafupi ndi anthu am'mudzi."],
p18:["E1. Pulogalamuyi ikugwirizana ndi kusintha kwa zosowa ndi chikhalidwe cha anthu.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi simayankha kusintha kwa zosowa za anthu am'mudzi (monga kusefukira kwa madzi, zilala, njala ya nyengo, kubwera  kwa njira zamakono, kusintha kwa ndale, ndi zina zotero).",
"Pulogalamuyi imatha kusintha zina.",
"Pulogalamuyi imatha kusintha momwe zingafunikire kusintha zosowa za anthu ammudzi kuphatikiza zomwe zimadza ndi zovuta kapena masoka.",
"Purogalamuyi iri ndi kuthekera kosintha  zosowa za anthu am'mudzi kuphatikizapo zomwe zimadza chifukwa cha zovuta kapena ngozi  ndipo imakonza kuthekera / njira zothetsera mavuto omwewo mtsogolomu.."],
p19:["E2. Mayendedwe a Pulogalamu ya CLD (ie, nthawi yochitika, kuchitika kangati, ndi kutalika kwa kuyanjana ndi anthu a m'mudzi ) zimatsimikizidwa ndi  anthu am'mudzi.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Anthu am'mudzi samatenga nawo mbali posankha m'mene  pulogalamuyo ikuyendera.",
"Anthu am'mudzi akudziwitsidwa za mayendedwe a pulogalamuyi.",
"Anthu ena am'mudzi amafunsidwa kupereka maganizo awo posankha momwe ntchitoyi ikuyendera.",
"Mamembala onse ammudzi, kuphatikiza oyimilira a magulu oponderezedwa, amafunsidwa posankha momwe pulogalamuyo ikuyendera.."],
p20:["F1. Pulogalamuyi imapanga ubale wabwino pakati pa magulu  osiyanasiyana  azachuma- olemera ndi osauka; osauka ndi osauka.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi siyiganizira za kusiyana kwachuma.",
"Pulogalamuyi imapanga ubale pakati pa osauka ndi osauka.",
"Pulogalamuyi imabweletsa pamodzi  olemera ndi osauka pazokambirana ndi zokambirana.",
"Pulogalamuyi imabweletsa pamodzi  olemera ndi osauka kugwira ntchito limodzi kuti akwaniritse cholinga chimodzi.."],
p21:["F2. Pulogalamuyi imathandizira kupanga  ubale abwino pakati pa magulu omwewo komanso pa anthu amitundu yosiyanasiyana, magulu, zipembedzo, ndi zina zotero.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi siyiganizira za kusiyana kwa mitundu ya anthu / mafuko / zipembedzo.",
"Pulogalamuyi imamanga ubale pakati pa anthu amtundu umodzi / fuko / chipembedzo chimodzi kuti agwire ntchito limodzi kuti asinthe.",
"Pulogalamuyi imaphatikizapo anthu ochokera m'mitundu / mafuko / zipembedzo zosiyanasiyana pazokambirana ndi kukambirana.",
"Pulogalamuyi imamanga ubale pakati pa anthu ochokera m'mitundu / mafuko / zipembedzo zosiyanasiyana kuti agwire ntchito limodzi kuti asinthe.."],
p22:["F3. Pulogalamuyi imapanga ubale wabwino pakati pa anthu osiyanasiyana malinga ndi chilengedwe - amayi ndi amayi komanso, pakati pa amuna ndi akazi.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi sigwira ntchito ndi azimayi.",
"Pulogalamuyi imapanga maubwenzi pakati pa amayi a gulu limodzi.",
"Pulogalamuyi imapanga ubale pakati pa magulu onse a amayi KAPENA pakati pa amayi ndi abambo.",
"Pulogalamuyi imapanga maubwenzi pakati pa magulu onse a amayi NDI pakati pa amayi ndi abambo NDIPO (poyenera kutero) pakati pa amayi ndi magulu omwe ali ndi zikhulupiriro zosiyana pankhani ya kupendekera"],
p23:["F4. Pulogalamuyi imalumikiza madera kapena atsogoleri awo kumidzi ina ndi atsogoleri awo m'maboma, zigawo, kapena maiko.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi sipanga njira zolumikizirana  ndi maulalo am'mudzi.",
"Pulogalamuyi imapanga maulalo pakati pa madera/atsogoleri ochokera  m'boma lomwelo.",
"Pulogalamuyi imapanga maulalo pakati pa madera / atsogoleri am'madera m'boma lonse / boma / chigawo / dziko.",
"Pulogalamuyi imapanga mgwirizano pakati pa madera mdziko lonse/magawo/mayiko kuti achitepo kanthu.."],
p24:["G1. Magulu am'mudzi a pulogalamuyi amagwira ntchito limodzi ndi mabungwe a maboma ang'ono ndi a zisudzo.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Pulogalamuyi kapena magulu ake am'deralo ndi mabungwe a maboma ang'ono  omwe alipo ndi ochita zisudzo amapereka mauthenga / mauthenga otsutsana.",
"Pulogalamuyi kapena magulu ake am'mudzi ndi mabungwe a maboma ang'ono ofunikira omwe alipo kale sagwira ntchito limodzi  mpang'ono pomwe(ngakhale amayesetsa kukwaniritsa zolinga zomwezo).",
"Pulogalamuyi kapena magulu ake am'mudzi ndi mabungwe a maboma ang'ono ofunikira omwe alipo kale  ndi azisudzo  amagwirira ntchito limodzi nthawi zina pazinthu zina.",
"Pulogalamuyi ndi magulu ake am'mudzi ndi mabungwe a maboma ang'ono/azisudzo kawiri-kawiri  amagwirira ntchito limodzi ndikuthandizana.."],
p25:["H1. Anthu am'mudzi amayang'anira zochitika zikulu-zikulu  ndi momwe pulogalamuyo ikuyendera.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Palibe kuyanaga'anira  kotengapo mbali  anthu am'mudzi.",
"Kuyang'anira ndi anthu a m'midzi  kumachitika nthawi zina.",
"Kuyang'anira dera kumachitika pafupipafupi, koma kumayendetsedwa ndi pulogalamu kapena ogwira ntchito m'bungwe.",
"Kuyang'anira dera kumachitika pafupipafupi ndipo kumayendetsedwa ndi anthu am'mudzi kapena mabungwe.."],
p26:["H2. Kuunika kotengapo mbali  kumachitika.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Palibe kuunika kochitika ndi anthu a m'mdera.",
"Anthu am'mudzi amatenga nawo mbali mu CHIMODZI kapena ZIWIRI  mwa zochitika izi: 1) Kukonzekera; 2) Kusonkhanitsa Deta; 3) Kusanthula; 4) Kutsimikizika; 5) Mapeto ndi Malangizo; 6) Kukonzekera zochita.",
"Anthu ammudzi akutenga nawo mbali muzochita zambiri (ZITATU kapena ZINAYI) mwa izi: 1) Kukonzekera; 2) Kusonkhanitsa Deta; 3) Kusanthula; 4) Kutsimikizika; 5) Mapeto ndi Malangizo; 6) Kukonzekera zochita.",
"Mamembala ndi ofunika kwambiri pazochitika ZONSE: 1) Kukonzekera; 2) Kusonkhanitsa Deta; 3) Kusanthula; 4) Kutsimikizika; 5) Mapeto ndi Malangizo; 6) Kukonzekera zochita.."],
p27:["H3. Ntchito zokhudza kuyang'anira ndi kuwunika  zimayang'ana momwe pulogalamuyi imagwirira ntchito ndi kupindulitsa magulu osiyanasiyana a anthu kuphatikizapo amayi, anthu a ulumali, okalamba, anthu ochokera m'madera ochepa, obwera kudzagwira ntchito mderalo.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Anthu am'mudzi sadziwa chifukwa satenga nawo mbali pantchito yoyang'anira ndi kuwunika (M&E) KAPENA anthu am'mudzi akutenga nawo mbali koma machitidwe a M&E saganizira magulu osiyanasiyana a anthu pomwe akusonkhanitsa kapena kusanthula zomwe zalembedwazo.",
"Kuyang'anira ndi kuunika kumasonkhanitsa ndi kusanthula zolembedwa ndi cholinga  chomvetsetsa   momwe pulogalamuyi imagwirira ntchito ndi kupindulira  magulu ena am'mudzi (monga amuna ndi akazi, koma osati anthu a ulumala).",
"Kuyang'anira ndi kuwunika kumasonkhanitsa ndikusanthula zambiri kuti amvetsetse momwe pulogalamuyi imagwirira ntchito ndi kupindulitsa magulu ambiri am'mudzi.",
"Kuyang'anira ndi kuunika kumasonkhanitsa ndikusanthula zinthu ndi cholinga chomvetsetsa m'mene  pulogalamuyo imagwirira ntchito ndi kupindulitsa magulu onse osiyanasiyana a anthu.."],
p28:["I1. Otsogolera amasankha nthawi, malo, ndi malo amisonkhano kuti aliyense athe kutenga nawo mbali.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Otsogolera amasankha nthawi, malo, ndi makonzedwe amisonkhanoyo potengera zomwe iwowo akufuna kapena za anthu ochepa chabe m’deralo.",
"Otsogolera amafikira  osachepera chimodzi mwa izi: Kukonza misonkhano pa nthawi , malo, kapena malo omwe amalola anthu onse kutenga nawo mbali ndikulankhula momasuka.",
"Otsogolera amafikira  osachepera ziwiri mwa izi: kukonza misonkhano mu nthawi, malo, ndi makonzedwe omwe amalola anthu onse kutenga nawo mbali ndikulankhula momasuka.",
"Otsogolera amafikira zonse mwa  zitatu izi: kukonza misonkhano pa nthawi, malo, ndi malo amene amalola anthu onse kutenga nawo mbali ndi kulankhula momasuka.."],
p29:["I2. Otsogolera polojekiti ndi aulemu ndipo amalimbikitsa kukambirana.",
"Sindikudziwa/ uthengawu ngosakwanira",
"Otsogolera amaphunzitsa ndi kuwuza anthu zoyenera kuchita, osamvera, ndipo ndi opanda ulemu.",
"Otsogolera amamvetsera ndi kuchitira anthu ulemu.",
"Otsogolera amamvetsera maganizo awo, kuchitira anthu ulemu, ndi kulimbikitsa ophunzira onse kuti alankhule.",
"Otsogolera amamvetsera, kuchitira ulemu anthu, ndi kulimbikitsa anthu kuti azilankhulana.."],
p30:["I3. Titapita kumisonkhano ndi otsogolera, timamva kuti:",
"Sindikudziwa/ uthengawu ngosakwanira",
"Kunali kutaya nthawi chabe; timangopezekapo chifukwa tiyenera kutero.",
"Tikumva malingaliro atsopano koma sitikudziwa choti tichite nawo.",
"Timamva malingaliro atsopano ndipo otsogolera amatiuza momwe tingawachitire nawo.",
"Timamva malingaliro ndi  maphunziro atsopano ndipo pamodzi timaasankha momwe tingachitire nawo.."],
p31:["I4. (Kwa otsogolera okha) Timamva kuthandizidwa (kulandira maphunziro nthawi zonse, kumvetsetsa zomwe tikuchita ndi chifukwa chake, kukhala ndi kasinthasintha ndi bajeti) ndi bungwe lokhazikitsa ntchito / bungwe la boma kuti ligwire ntchito yathu",
"Sindikudziwa/ uthengawu ngosakwanira",
"Bungwe lokhazikitsa / bungwe la boma silichita khama kuthandizira ntchito yathu",
"Timalandira chithandizo m’mbali ziwiri mwa izi a) timalandira maphunziro nthawi zonse (osati kamodzi kokha) m’chinenero chathu, b) timadziwa zimene tikuchita komanso chifukwa chake zili zofunika, c) timatha kusintha chiwerengero cha misonkhano imene timatsogolera komanso misonkhano ndi nthawi yawo kuti igwirizane ndi zosowa za m’deralo, d) timapatsidwa malo ochitira misonkhano ndi zipangizo zonse zoyendetsera misonkhano ndi bungwe lomwe likugwira ntchito, e) ntchito yathu ndi yokwanira (yosayembeyembekezeredwa kufikira midzi yambiri kapena mtunda wautali kwambiri kapena kuchita misonkhano yambiri)",
"Timalandira chithandizo m’magawo atatu awa a) timalandira maphunziro nthawi zonse (osati nthawi imodzi) m’chinenero chathu, b) timadziwa zimene tikuchita komanso chifukwa chake zili zofunika, c) tingathe kusintha chiwerengero cha misonkhano imene timayang’anira ndi  nthawi kuti igwirizane ndi zosowa za m’deralo, d) timapatsidwa malo ochitira misonkhano ndi zipangizo zonse zoyendetsera misonkhano ndi bungwe lomwe likugwira ntchito, e) ntchito yathu ndi yokwanira (yosayembekezeredwa kuti ifike kumidzi yambiri kapena mtunda wautali kwambiri kapena kuchita misonkhano yambiri)",
"Timalandira thandizo m'mbali ZONSE za madera awa) timalandira maphunziro pafupipafupi (osati nthawi imodzi) m'chilankhulo chathu, b) timadziwa zomwe tikuchita komanso chifukwa chake zili zofunika, c) titha kusintha kuchuluka kwa misonkhano yomwe timatsogolera komanso nthawi kuti igwirizane ndi zosowa za m’deralo, d) timapatsidwa malo ochitira misonkhano ndi zipangizo zonse zoyendetsera misonkhano ndi bungwe lomwe likugwira ntchito, e) ntchito yathu ndi yokwanira (yosayembekezeredwa kuti ifike kumidzi yambiri kapena mtunda wautali kwambiri kapena kuchita misonkhano yambiri)"]
}
